# Libraries

In [1]:
import pandas as pd

import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

# APPLICANT Dataset

In [2]:
df_original_1 = pd.read_excel(r"C:\Users\DELL\Downloads\Applicant_Data.xlsx")
applicant = df_original_1
applicant.head(5)

,Reference_ID,Given_Name,Last_Name,Major,Country,Received_At,University,Citizenship,Intake,College_1st_Choice,...,Phone_Number_2,Admit_Date,Most_Recent_Released_Decision,Application_Source,Is_Global_Grad,SEVIS_ID,Official_University_email_address,Application_Agency_Code,Created_At,Modified_At
0,1289258,Adekunle,Adefowoju,BusinessAdministration(MBA)ProfessionalMBA(Eve...,Nigeria,1744630000000,Saint Louis University,Nigeria,Fall 2024,Health Data Science (MS),...,7067957137,NaN,NaN,ERXWebAPP,NaN,NaN,adekunle.adefowoju@slu.edu,NaN,1744630000000,1744630000000
1,1294844,Emmanuel,AduNyarko,Analytics(MS)atSaintLouis,Ghana,1744630000000,Saint Louis University,Ghana,Fall 2024,Information Systems (MS),...,233000000000,NaN,NaN,ERXWebAPP,NaN,NaN,emmanuel.adunyarko@slu.edu,NaN,1744630000000,1744630000000
2,1302877,Ogochukwu,Agina,Analytics(MS)atSaintLouis,Nigeria,1744630000000,Saint Louis University,Nigeria,Fall 2024,Computer Science (MS),...,7037993011,NaN,NaN,ERXWebAPP,NaN,NaN,ogochukwu.agina@slu.edu,NaN,1744630000000,1744630000000
3,1299192,Afia,AgyapongAnsong,InformationSystems(MS)atSaintLouis,Ghana,1744630000000,Saint Louis University,Ghana,Fall 2024,Information Systems (MS),...,234000000000,NaN,NaN,ERXWebAPP,NaN,NaN,afia.agyapongansong@slu.edu,NaN,1744630000000,1744630000000
4,1324269,RebeccaAgyeiwaa,Agyare,PublicHealth(MPH)EpidemiologyatSaintLouis,Ghana,1744630000000,Saint Louis University,Ghana,Fall 2024,Supply Chain Management (MS),...,NaN,NaN,NaN,INTO,NaN,NaN,rebeccaagyeiwaa.agyare@slu.edu,NaN,1744630000000,1744630000000

In [3]:
applicant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6894 entries, 0 to 6893
Data columns (total 30 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Reference_ID                       6894 non-null   int64
 1   Given_Name                         6894 non-null   object
 2   Last_Name                          6894 non-null   object
 3   Major                              6893 non-null   object
 4   Country                            19 non-null     object
 5   Received_At                        6894 non-null   int64
 6   University                         6894 non-null   object
 7   Citizenship                        6892 non-null   object
 8   Intake                             6894 non-null   object
 9   College_1st_Choice                 19 non-null     object
 10  Phone_Number                       6800 non-null   object
 11  Street_1                           6853 non-null   object
 12  Street_2                           1729 non-null   object
 13  Street_3                           63 non-null     object
 14  City                               6889 non-null   object
 15  Region                             6575 non-null   object
 16  Postal                             6396 non-null   object
 17  Email_ID                           6894 non-null   object
 18  Date_of_Birth                      6875 non-null   object
 19  Comments                           0 non-null      float64
 20  Phone_Number_2                     190 non-null    object
 21  Admit_Date                         0 non-null      float64
 22  Most_Recent_Released_Decision      6748 non-null   object
 23  Application_Source                 6893 non-null   object
 24  Is_Global_Grad                     6875 non-null   object
 25  SEVIS_ID                           2606 non-null   object
 26  Official_University_email_address  6831 non-null   object
 27  Application_Agency_Code            2567 non-null   object
 28  Created_At                         6894 non-null   int64
 29  Modified_At                        6894 non-null   int64
dtypes: float64(2), int64(4), object(24)
memory usage: 1.6+ MB

In [4]:
applicant.isna().sum()

Reference_ID                            0
Given_Name                              0
Last_Name                               0
Major                                   1
Country                              6875
Received_At                             0
University                              0
Citizenship                             2
Intake                                  0
College_1st_Choice                   6875
Phone_Number                           94
Street_1                               41
Street_2                             5165
Street_3                             6831
City                                    5
Region                                319
Postal                                498
Email_ID                                0
Date_of_Birth                          19
Comments                             6894
Phone_Number_2                       6704
Admit_Date                           6894
Most_Recent_Released_Decision         146
Application_Source                      1
Is_Global_Grad                         19
SEVIS_ID                             4288
Official_University_email_address      63
Application_Agency_Code              4327
Created_At                              0
Modified_At                             0
dtype: int64

In [5]:
applicant['Official_University_email_address'].unique()

array(['adekunle.adefowoju@slu.edu', 'emmanuel.adunyarko@slu.edu',
       'ogochukwu.agina@slu.edu', ..., 'amoohgyan.amoohgyan@slu.edu',
       'opeyemi.olabintan@slu.edu', 'paulinus.daeli@slu.edu'],
      shape=(6831,), dtype=object)

In [6]:
applicant.columns

Index(['Reference_ID', 'Given_Name', 'Last_Name', 'Major', 'Country',
       'Received_At', 'University', 'Citizenship', 'Intake',
       'College_1st_Choice', 'Phone_Number', 'Street_1', 'Street_2',
       'Street_3', 'City', 'Region', 'Postal', 'Email_ID', 'Date_of_Birth',
       'Comments', 'Phone_Number_2', 'Admit_Date',
       'Most_Recent_Released_Decision', 'Application_Source', 'Is_Global_Grad',
       'SEVIS_ID', 'Official_University_email_address',
       'Application_Agency_Code', 'Created_At', 'Modified_At'],
      dtype='object')

In [7]:
applicant.shape

(6894, 30)

#Data cleaning

In [8]:
applicant['Created_At'] = pd.to_datetime(applicant['Created_At'])
applicant['Modified_At'] = pd.to_datetime(applicant['Modified_At'])
applicant['Most_Recent_Released_Decision'] = pd.to_datetime(applicant['Most_Recent_Released_Decision'])
applicant['Received_At'] = pd.to_datetime(applicant['Received_At'])
applicant['Date_of_Birth'] = pd.to_datetime(applicant['Date_of_Birth'])

In [9]:
applicant['Major'].fillna('Others', inplace = True)

applicant.rename(columns = {"Major": "Departments"}, inplace = True) 

applicant['Citizenship'].fillna('Others', inplace = True)

applicant['Street_1'].fillna('Unknown', inplace= True)

applicant['City'].fillna('Others', inplace= True)

applicant['Region'].fillna('Others', inplace= True)

applicant['Postal'].fillna('Others', inplace= True)

mean_date = applicant['Date_of_Birth'].mean()
applicant['Date_of_Birth'] = applicant['Date_of_Birth'].fillna(mean_date)

meean_date = applicant['Most_Recent_Released_Decision'].mean()
applicant['Most_Recent_Released_Decision'] = applicant['Most_Recent_Released_Decision'].fillna(meean_date)

applicant['Is_Global_Grad'].fillna('Unknown', inplace= True)

applicant['SEVIS_ID'].fillna('Unknown', inplace= True)

applicant['Official_University_email_address'].fillna('Unknown', inplace= True)

applicant['Application_Agency_Code'].fillna('Others', inplace= True)

applicant['Application_Source'].fillna('Others', inplace= True)

applicant['Phone_Number'].fillna('No phone Number', inplace= True)

#Data Manipulation

In [10]:
applicant.drop('Country', axis= 1, inplace= True)

applicant.drop('College_1st_Choice', axis= 1, inplace= True)

applicant.drop('Street_2', axis= 1, inplace= True)

applicant.drop('Street_3', axis= 1, inplace= True)

applicant.drop ('Comments', axis= True, inplace= True)

applicant.drop ('Phone_Number_2', axis= True, inplace= True)

applicant.drop ('Admit_Date', axis= True, inplace= True)

In [11]:
from datetime import datetime
#today = pd.Timestamp('today')

applicant['Age'] = (datetime.today() - applicant['Date_of_Birth']).dt.days // 365

#today.year - applicant['Date_of_Birth'].dt.year -((today.month, today.day) < (applicant['Date_of_Birth'].dt.month, applicant['Date_of_Birth'].dt.day))

In [12]:
applicant.isna().sum()

Reference_ID                         0
Given_Name                           0
Last_Name                            0
Departments                          0
Received_At                          0
University                           0
Citizenship                          0
Intake                               0
Phone_Number                         0
Street_1                             0
City                                 0
Region                               0
Postal                               0
Email_ID                             0
Date_of_Birth                        0
Most_Recent_Released_Decision        0
Application_Source                   0
Is_Global_Grad                       0
SEVIS_ID                             0
Official_University_email_address    0
Application_Agency_Code              0
Created_At                           0
Modified_At                          0
Age                                  0
dtype: int64

In [13]:
applicant[applicant.duplicated(subset=['Reference_ID'])] #Shows duplicated rows
applicant = applicant.drop_duplicates(subset=['Reference_ID'])
applicant.shape

(6893, 24)

In [14]:
applicant.tail(10)

,Reference_ID,Given_Name,Last_Name,Departments,Received_At,University,Citizenship,Intake,Phone_Number,Street_1,...,Date_of_Birth,Most_Recent_Released_Decision,Application_Source,Is_Global_Grad,SEVIS_ID,Official_University_email_address,Application_Agency_Code,Created_At,Modified_At,Age
6884,1390060,Funke,Ojo,Project Management (MS),1970-01-01 00:29:08.330,Saint Louis University,Nigeria,Fall 2026,No phone Number,No 5 Adeyinka Okunade close,...,1985-12-18,2025-05-19,Slate,Yes,Unknown,Unknown,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,40
6885,1438361,Grace,Irobi,Family Therapy (MA),1970-01-01 00:29:08.330,Saint Louis University,Nigeria,Fall 2026,+234 817 195 6635,"Umuchimanwiri, Obazu-Mbieri, Mbaitolu Local Go...",...,1991-08-22,2025-01-05,Slate,No,Unknown,grace.irobi@health.slu.edu,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,34
6886,1448408,Yuqi,Chen,Educational Leadership (PHD),1970-01-01 00:29:08.330,Saint Louis University,China,Fall 2026,+1 314-410-9411,212 S Meramec Ave Apt 1302,...,2000-01-04,2025-03-04,Slate,No,Unknown,iris.chen@slu.edu,No,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,26
6887,1449162,Evelyn,Arthur-Kwegyir,Educational Leadership (PHD),1970-01-01 00:29:08.330,Saint Louis University,Ghana,Fall 2026,+233 24 792 9024,M 255 Rose Hips Street CI-01059732,...,1978-11-02,2025-05-23,Slate,No,Unknown,evelyn.arthurkwegyir@slu.edu,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,47
6888,1442373,Leonard,Amooh Gyan,Geographic Information Sciences (MS),1970-01-01 00:29:08.330,Saint Louis University,Ghana,Fall 2026,+233 20 343 1710,No. 7 Obaahemaa Ampa Street,...,1992-05-06,2025-04-22,Slate,No,Unknown,amoohgyan.amoohgyan@slu.edu,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,33
6889,1424285,Avinash,Jha,Cybersecurity (MS),1970-01-01 00:29:08.330,Saint Louis University,Nepal,Fall 2026,+977 981-7895320,Kadam Chowk -2,...,1998-09-17,2025-05-19,Slate,Yes,Unknown,Unknown,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,27
6890,1440172,Samuel Opeyemi,Olabintan,Biomedical Engineering (PHD),1970-01-01 00:29:08.330,Saint Louis University,Nigeria,Fall 2026,+234 701 908 6202,"28,Fabukade Street,Shogunle",...,2002-04-21,2025-08-05,Slate,No,Unknown,opeyemi.olabintan@slu.edu,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,23
6891,1356764,Ama,Essel,Project Management (MS),1970-01-01 00:29:08.330,Saint Louis University,Ghana,Fall 2026,+233 24 808 6344,"C/O Jei River, Kasoa",...,1996-12-30,2025-05-23,Slate,Yes,Unknown,Unknown,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,29
6892,1381727,Jonathan,Cobbina,Information Systems (MS),1970-01-01 00:29:08.330,Saint Louis University,Ghana,Fall 2026,+233 55 673 0711,CG0209-5667,...,1999-12-26,2025-05-23,Slate,Yes,Unknown,Unknown,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,26
6893,1439190,Paulinus,Daeli,Theological Studies (PHD),1970-01-01 00:29:08.330,Saint Louis University,Indonesia,Fall 2026,+1 623-283-7260,2850 Abbey Plz,...,1998-02-20,2025-06-05,Slate,No,Unknown,paulinus.daeli@slu.edu,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,28

In [15]:
#Export = applicant.to_excel("Applicant_Cleaned.xlsx", sheet_name = "Applicant", index = False)
#Export

# CONNECT Dataset

In [16]:
df_original_2 = pd.read_excel(r"C:\Users\DELL\Downloads\Connect.xlsx")
connect = df_original_2
connect.head(5)

,Reference_ID,Deposit_Status,Assigned,Recieved_At,University,I_20_Status,Created_At,Modified_At
0,1320577,Yes,"Anna Kluemke, Mounika Bhuvana Maheswari Krishn...",4/14/2025 19:55,Saint Louis University,Yes,1740000000000,1740000000000
1,1356800,Yes,"Catherine Donahue, Jorge Jesus Pena Cevallos",4/14/2025 19:55,Saint Louis University,Yes,1740000000000,1740000000000
2,1356915,Yes,Ryan Stoeckel,4/14/2025 19:55,Saint Louis University,Yes,1740000000000,1740000000000
3,1319991,Yes,"Anna Kluemke, Mounika Bhuvana Maheswari Krishn...",4/14/2025 19:55,Saint Louis University,Yes,1740000000000,1740000000000
4,1266321,Yes,"Naresh Dama, Catherine Donahue",4/14/2025 19:55,Saint Louis University,Yes,1740000000000,1740000000000

In [17]:
connect.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34341 entries, 0 to 34340
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Reference_ID    34341 non-null  int64
 1   Deposit_Status  34341 non-null  object
 2   Assigned        14531 non-null  object
 3   Recieved_At     34341 non-null  object
 4   University      34341 non-null  object
 5   I_20_Status     34341 non-null  object
 6   Created_At      34341 non-null  int64
 7   Modified_At     34341 non-null  int64
dtypes: int64(3), object(5)
memory usage: 2.1+ MB

In [18]:
connect.isna().sum()

Reference_ID          0
Deposit_Status        0
Assigned          19810
Recieved_At           0
University            0
I_20_Status           0
Created_At            0
Modified_At           0
dtype: int64

In [19]:
connect['Recieved_At'] = pd.to_datetime(connect['Recieved_At'])

In [20]:
connect['Assigned'].fillna('Others', inplace= True)

In [21]:
connect[connect.duplicated(subset=['Reference_ID'])] #Shows duplicated rows
connect = connect.drop_duplicates(subset=['Reference_ID'])

In [22]:
connect.isna().sum()

Reference_ID      0
Deposit_Status    0
Assigned          0
Recieved_At       0
University        0
I_20_Status       0
Created_At        0
Modified_At       0
dtype: int64

In [23]:
connect.shape

(6875, 8)

In [24]:
#Export2 = connect.to_excel("Connect_Cleaned.xlsx", sheet_name = "Connect", index = False)
#Export2

# OUTREACH Dataset

In [25]:
df_original_3 = pd.read_excel(r"C:\Users\DELL\Downloads\Outreach_Data.xlsx")
outreach = df_original_3
outreach.head(5)

,Student_Full_Name,Program_Of_interest,Term,Application_Source,Global_Grad_Indicator,Deposit_Paid,Accepted_Admission,SEVIS_ID,I_20_In_Slate,Person_Email,Person_SLU_Email_Address,I_901_Status,Citizenship_(Primary),Application_Agency_Code,Contact_Number,Student_Status,Remarks,Appointment_Date
0,Chatarajupalli Dhruvakumar,Health Data Science (MS),Fall 2024,INTO,No,Yes,Yes,N0035601594,Yes,dhruvakumar1718@gmail.com,dhruvakumar.chatarajupalli@slu.edu,Payment,India,INTO SLU,7731891178,Visa approved,NaN,NaN
1,Dachuri Harika,Information Systems (MS),Fall 2024,Slate,Yes,Yes,Yes,N0035617247,Yes,dachuriharika@gmail.com,harika.dachuri@slu.edu,Payment,India,GRC05,8008504742,Outreach efforts,Not interested in SLU,NaN
2,Pamidi Sravani,Information Systems (MS),Fall 2024,INTO,Yes,Yes,Yes,N0034926841,Yes,pamidisravani888@gmail.com,sravani.pamidi@slu.edu,Payment,India,INTO SLU,9390377842,Appointment schedule,NaN,2025-07-22 00:00:00
3,Lakshmi Venkata Subrahmanyam Parise,Information Systems (MS),Fall 2024,INTO,Yes,Yes,Yes,N0035409324,Yes,subrahmanyamparise2024@gmail.com,parise.lakshmivenkatasubrahmanyam@slu.edu,Payment,India,INTO SLU,9347915699,Visa denied,NaN,NaN
4,Sarepalli Ben Jagadeesh,Supply Chain Management (MS),Fall 2024,INTO,Yes,Yes,Yes,N0035427864,Yes,sarepallibenjagadeesh@gmail.com,benjagadeesh.sarepalli@slu.edu,Payment,India,INTO SLU,9290688899,Visa approved,NaN,NaN

In [26]:
outreach.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1565 entries, 0 to 1564
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Student_Full_Name         1565 non-null   object
 1   Program_Of_interest       1565 non-null   object
 2   Term                      1565 non-null   object
 3   Application_Source        1565 non-null   object
 4   Global_Grad_Indicator     1565 non-null   object
 5   Deposit_Paid              1565 non-null   object
 6   Accepted_Admission        1565 non-null   object
 7   SEVIS_ID                  1565 non-null   object
 8   I_20_In_Slate             1565 non-null   object
 9   Person_Email              1565 non-null   object
 10  Person_SLU_Email_Address  1565 non-null   object
 11  I_901_Status              1565 non-null   object
 12  Citizenship_(Primary)     1565 non-null   object
 13  Application_Agency_Code   1221 non-null   object
 14  Contact_Number            1531 non-null   object
 15  Student_Status            1565 non-null   object
 16  Remarks                   817 non-null    object
 17  Appointment_Date          373 non-null    object
dtypes: object(18)
memory usage: 220.2+ KB

In [27]:
#outreach['Official_University_email_address'].unique()

In [28]:
outreach.isna().sum()

Student_Full_Name              0
Program_Of_interest            0
Term                           0
Application_Source             0
Global_Grad_Indicator          0
Deposit_Paid                   0
Accepted_Admission             0
SEVIS_ID                       0
I_20_In_Slate                  0
Person_Email                   0
Person_SLU_Email_Address       0
I_901_Status                   0
Citizenship_(Primary)          0
Application_Agency_Code      344
Contact_Number                34
Student_Status                 0
Remarks                      748
Appointment_Date            1192
dtype: int64

#### Data Cleaning and Manipulation

In [29]:
outreach.rename(columns = {"Person_SLU_Email_Address": "Official_University_email_address"}, inplace = True) 

outreach['Contact_Number'].fillna('No phone Number', inplace= True)

outreach['Application_Agency_Code'].fillna('Others', inplace=True)

outreach['Remarks'].fillna('Not provided', inplace= True)

In [30]:
outreach.drop('Appointment_Date', axis= 1, inplace= True)

In [31]:
outreach[outreach.duplicated(subset=['Official_University_email_address'])] #Shows duplicated rows
outreach = outreach.drop_duplicates(subset=['Official_University_email_address'])
outreach.shape

(1560, 17)

In [32]:
outreach.isna().sum()

Student_Full_Name                    0
Program_Of_interest                  0
Term                                 0
Application_Source                   0
Global_Grad_Indicator                0
Deposit_Paid                         0
Accepted_Admission                   0
SEVIS_ID                             0
I_20_In_Slate                        0
Person_Email                         0
Official_University_email_address    0
I_901_Status                         0
Citizenship_(Primary)                0
Application_Agency_Code              0
Contact_Number                       0
Student_Status                       0
Remarks                              0
dtype: int64

In [33]:
outreach.head(5)

,Student_Full_Name,Program_Of_interest,Term,Application_Source,Global_Grad_Indicator,Deposit_Paid,Accepted_Admission,SEVIS_ID,I_20_In_Slate,Person_Email,Official_University_email_address,I_901_Status,Citizenship_(Primary),Application_Agency_Code,Contact_Number,Student_Status,Remarks
0,Chatarajupalli Dhruvakumar,Health Data Science (MS),Fall 2024,INTO,No,Yes,Yes,N0035601594,Yes,dhruvakumar1718@gmail.com,dhruvakumar.chatarajupalli@slu.edu,Payment,India,INTO SLU,7731891178,Visa approved,Not provided
1,Dachuri Harika,Information Systems (MS),Fall 2024,Slate,Yes,Yes,Yes,N0035617247,Yes,dachuriharika@gmail.com,harika.dachuri@slu.edu,Payment,India,GRC05,8008504742,Outreach efforts,Not interested in SLU
2,Pamidi Sravani,Information Systems (MS),Fall 2024,INTO,Yes,Yes,Yes,N0034926841,Yes,pamidisravani888@gmail.com,sravani.pamidi@slu.edu,Payment,India,INTO SLU,9390377842,Appointment schedule,Not provided
3,Lakshmi Venkata Subrahmanyam Parise,Information Systems (MS),Fall 2024,INTO,Yes,Yes,Yes,N0035409324,Yes,subrahmanyamparise2024@gmail.com,parise.lakshmivenkatasubrahmanyam@slu.edu,Payment,India,INTO SLU,9347915699,Visa denied,Not provided
4,Sarepalli Ben Jagadeesh,Supply Chain Management (MS),Fall 2024,INTO,Yes,Yes,Yes,N0035427864,Yes,sarepallibenjagadeesh@gmail.com,benjagadeesh.sarepalli@slu.edu,Payment,India,INTO SLU,9290688899,Visa approved,Not provided

In [34]:
#Export3 = outreach.to_excel("Outreach_Cleaned.xlsx", sheet_name = "Outreach", index = False)
#Export3

# SEVIS Dataset

In [35]:
df_original_4 = pd.read_excel(r"C:\Users\DELL\Downloads\SEVIS.xlsx")
sevis = df_original_4
sevis.head(5)

,SEVIS_ID,NonImmigrant_ID,FIN_ID,SEVIS_Status,Status_Change_Date,Class_of_Admission,Surname_Or_Primary_Name,Given_Name,Suffix,Preferred_Name,...,I-901_Transaction_Type,I-901_Transaction_Date,I-901_Transaction_Amount,I-901_Fee_Payment_Receipt,Border_Commuter_Student,Correction_Request_Pending,Cancellation_Reason,Overall_Remarks,Length_of_Next_Break_of_Vacation,OPT_Portal
0,N0035966363,35966363,NaN,INITIAL,6/27/2024,F-1,Anya,Kelechi Amaechi,NaN,Kelechi Anya,...,Payment,11/20/2023,350.0,AAA2405170028,N,N,NaN,Student must report to university within 7 day...,0,N
1,N0036036214,36036214,NaN,INITIAL,7/23/2024,F-1,Kommareddy,Sunand Chowdary,NaN,Sunand Kommareddy,...,NaN,NaN,NaN,NaN,N,N,NaN,Student must report to university within 7 day...,0,N
2,N0035434583,35434583,NaN,INITIAL,3/21/2024,F-1,Siva,Mukesh,NaN,Mukesh,...,NaN,NaN,NaN,NaN,N,N,NaN,Student must report to university within 7 day...,0,N
3,N0035831856,35831856,NaN,INITIAL,5/28/2024,F-1,Palaparthi,Yehoshuva,NaN,Yehoshuva Palaparthi,...,Payment,2023-07-12 00:00:00,350.0,CCC2406895590,N,N,NaN,Student must report to university within 7 day...,0,N
4,N0035686561,35686561,NaN,INITIAL,2024-02-05 00:00:00,F-1,Manchanpally,Soumith Reddy,NaN,Soumith Reddy,...,NaN,NaN,NaN,NaN,N,N,NaN,Student must report to university within 7 day...,0,N

In [36]:
sevis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3852 entries, 0 to 3851
Columns: 123 entries, SEVIS_ID to OPT_Portal
dtypes: float64(30), int64(7), object(86)
memory usage: 3.6+ MB

In [37]:
sevis['Length_of_Next_Break_of_Vacation'].unique()

array([0])

In [38]:
sevis.shape

(3852, 123)

In [39]:
sevis.iloc[:, :20].isna().sum()

SEVIS_ID                         0
NonImmigrant_ID                  0
FIN_ID                        3730
SEVIS_Status                     0
Status_Change_Date               0
Class_of_Admission               0
Surname_Or_Primary_Name          0
Given_Name                     150
Suffix                        3852
Preferred_Name                   0
SEVIS_Legacy_First_Name       3852
SEVIS_Legacy_Middle_Name      3852
SEVIS_Legacy_Last_Name        3852
Country_of_Birth                 0
City_of_Birth                 3762
Date_of_Birth                    1
Country_of_Citizenship           0
Gender                           0
US_Physical_Address_Status    3822
US_Physical_Address_1         3822
dtype: int64

#### Data Cleaning and Manipulation

In [40]:
sevis['Status_Change_Date'] = pd.to_datetime(sevis['Status_Change_Date'])
sevis['Date_of_Birth'] = pd.to_datetime(sevis['Date_of_Birth'])

sevis['I-901_Transaction_Date'] = pd.to_datetime(sevis['I-901_Transaction_Date'])
sevis['Date_of_Last_Event'] = pd.to_datetime(sevis['Date_of_Last_Event'])
sevis['Program_Start_Date'] = pd.to_datetime(sevis['Program_Start_Date'])
sevis['Program_End_Date'] = pd.to_datetime(sevis['Program_End_Date'])
sevis['Initial_Session_Start_Date'] = pd.to_datetime(sevis['Initial_Session_Start_Date'])
sevis['Current_Session_Start_Date'] = pd.to_datetime(sevis['Current_Session_Start_Date'])

sevis.rename(columns = {"Email": "Official_University_email_address"}, inplace = True)

In [41]:
sevis['Given_Name'].fillna('Not Provided', inplace=True)
sevis['Foreign_City'].fillna('Others', inplace=True)
sevis['Official_University_email_address'].fillna('Not Provided', inplace=True)
sevis['No_Phone_Indicator'].fillna('Not Provided', inplace=True)
sevis['Dependent_Expenses'].fillna(sevis['Dependent_Expenses'].mean(), inplace=True)
sevis['Other_Costs'].fillna(sevis['Other_Costs'].mean(), inplace=True)
sevis['Funds_From_This_School'].fillna(sevis['Funds_From_This_School'].mean(), inplace=True)
sevis['School_Fund_Type'].fillna('Others', inplace=True)
sevis['Funds_From_Other_Sources'].fillna(sevis['Funds_From_Other_Sources'].mean(), inplace=True)
sevis['Other_Source_Type'].fillna('Others', inplace=True)
sevis['On-Campus_Employment'].fillna(sevis['On-Campus_Employment'].mean(), inplace=True)
sevis['Student_Has_English_Proficiency'].fillna('Unknown', inplace=True)
sevis['I-901_Transaction_Type'].fillna('Others', inplace=True)
meeaan_date = sevis['I-901_Transaction_Date'].mean()
sevis['I-901_Transaction_Date'] = sevis['I-901_Transaction_Date'].fillna(meeaan_date)
meann_date = sevis['Date_of_Birth'].mean()
sevis['Date_of_Birth'] = sevis['Date_of_Birth'].fillna(meann_date)
sevis['I-901_Transaction_Amount'].fillna(sevis['I-901_Transaction_Amount'].mean(), inplace=True)
sevis['I-901_Fee_Payment_Receipt'].fillna('Unknown', inplace=True)
sevis['Overall_Remarks'].fillna('Not Provided', inplace=True)
sevis['Border_Commuter_Student'].fillna('Others', inplace=True)

In [42]:
# Replacing values in a column
#sevis["PartTimeJob"].replace({"Yes": 1, "No": 0}, inplace = True)

In [43]:
sevis.drop('FIN_ID', axis= 1, inplace=True)
sevis.drop('Suffix', axis= 1, inplace=True)
sevis.drop('SEVIS_Legacy_First_Name', axis= 1, inplace=True)
sevis.drop('SEVIS_Legacy_Middle_Name', axis= 1, inplace=True)
sevis.drop('SEVIS_Legacy_Last_Name', axis= 1, inplace=True)
sevis.drop('City_of_Birth', axis= 1, inplace=True)
sevis.drop('US_Physical_Address_Status', axis= 1, inplace=True)
sevis.drop('US_Physical_Address_1', axis= 1, inplace=True)
sevis.drop('US_Physical_Address_2', axis= 1, inplace=True)

sevis.drop('US_Physical_City', axis= 1, inplace=True)
sevis.drop('US_Physical_State', axis= 1, inplace=True)
sevis.drop('US_Physical_Postal_Code', axis= 1, inplace=True)
sevis.drop('US_Physical_Routing_Code', axis= 1, inplace=True)
sevis.drop('US_Mailing_Address_Status', axis= 1, inplace=True)
sevis.drop('US_Mailing_Address_1', axis= 1, inplace=True)
sevis.drop('US_Mailing_Address_2', axis= 1, inplace=True)
sevis.drop('US_Mailing_City', axis= 1, inplace=True)

sevis.drop('US_Mailing_State', axis= 1, inplace=True)
sevis.drop('US_Mailing_Postal_Code', axis= 1, inplace=True)
sevis.drop('US_Mailing_Routing_Code', axis= 1, inplace=True)
sevis.drop('Foreign_Address_2', axis= 1, inplace=True)
sevis.drop('Foreign_State_Province', axis= 1, inplace=True)
sevis.drop('Foreign_Postal_Code', axis= 1, inplace=True)
sevis.drop('US_Telephone', axis= 1, inplace=True)

sevis.drop('Foreign_Telephone_Country_Code', axis= 1, inplace=True)
sevis.drop('Foreign_Telephone', axis= 1, inplace=True)
sevis.drop('Passport_Name', axis= 1, inplace=True)
sevis.drop('Passport_Number', axis= 1, inplace=True)
sevis.drop('Passport_Expiration_Date', axis= 1, inplace=True)
sevis.drop('Passport_Country_of_Issuance', axis= 1, inplace=True)
sevis.drop('Visa_Number', axis= 1, inplace=True)
sevis.drop('Visa_Issuance_Date', axis= 1, inplace=True)

sevis.drop('Visa_Expiration_Date', axis= 1, inplace=True)
sevis.drop('Visa_Issuance_Post', axis= 1, inplace=True)
sevis.drop('Port_of_Entry', axis= 1, inplace=True)
sevis.drop('Date_of_Entry', axis= 1, inplace=True)
sevis.drop('I_94_Admission_Number', axis= 1, inplace=True)
sevis.drop('Port_of_Departure', axis= 1, inplace=True)
sevis.drop('Date_of_Departure', axis= 1, inplace=True)
sevis.drop('Other_Costs_Comment', axis= 1, inplace=True)

sevis.drop('Cancellation_Reason', axis= 1, inplace=True)
sevis.drop('Termination_Reason', axis= 1, inplace=True)
sevis.drop('Other_Termination_Comment', axis= 1, inplace=True)
sevis.drop('Major_2_Description', axis= 1, inplace=True)
sevis.drop('Minor_Description', axis= 1, inplace=True)
sevis.drop('Current_Session_End_Date', axis= 1, inplace=True)
sevis.drop('Next_Session_Start_Date', axis= 1, inplace=True)
sevis.drop('Last_Session', axis= 1, inplace=True)
sevis.drop('Study_Research_Abroad', axis= 1, inplace=True)
sevis.drop('Thesis_Or_Dissertation', axis= 1, inplace=True)
sevis.drop('English_Is_Not_Required_Because', axis= 1, inplace=True)
sevis.drop('Length_of_Next_Break_of_Vacation', axis= 1, inplace=True)
sevis.drop('Minor_Code', axis= 1, inplace=True)

In [44]:
sevis[sevis.duplicated(subset=['Official_University_email_address'])] #Shows duplicated rows
sevis = sevis.drop_duplicates(subset=['Official_University_email_address'])
sevis.shape

(3837, 70)

In [45]:
sevis.iloc[:, :20].head(5)

,SEVIS_ID,NonImmigrant_ID,SEVIS_Status,Status_Change_Date,Class_of_Admission,Surname_Or_Primary_Name,Given_Name,Preferred_Name,Country_of_Birth,Date_of_Birth,Country_of_Citizenship,Gender,Foreign_Address_1,Foreign_City,Foreign_Country,Official_University_email_address,No_Phone_Indicator,Number_of_Months_(for_funding),Tuition_Fees,Living_Expenses
0,N0035966363,35966363,INITIAL,2024-06-27,F-1,Anya,Kelechi Amaechi,Kelechi Anya,NIGERIA,1995-01-26,NIGERIA,FEMALE,"32, Samuel Street, Akowonjo road, Egbeda",Lagos,NIGERIA,kelechi.anya@slu.edu,Y,9,21000,18150
1,N0036036214,36036214,INITIAL,2024-07-23,F-1,Kommareddy,Sunand Chowdary,Sunand Kommareddy,INDIA,2005-10-16,INDIA,MALE,"5-1-84/7/402, GKS Arunodaya enclave",Medchal,INDIA,sunand.kommareddy@slu.edu,Y,9,55614,21350
2,N0035434583,35434583,INITIAL,2024-03-21,F-1,Siva,Mukesh,Mukesh,INDIA,2003-07-31,INDIA,MALE,No 1 lakshmi amml street,Chennai,INDIA,mukesh.siva@slu.edu,Y,9,21000,18150
3,N0035831856,35831856,INITIAL,2024-05-28,F-1,Palaparthi,Yehoshuva,Yehoshuva Palaparthi,INDIA,2002-08-18,INDIA,MALE,"D No: 1-36B, Ramayapalem Addanki",Bapatla,INDIA,yehoshuva.palaparthi@slu.edu,Y,9,21000,18150
4,N0035686561,35686561,INITIAL,2024-02-05,F-1,Manchanpally,Soumith Reddy,Soumith Reddy,INDIA,2002-04-19,INDIA,MALE,4-2-207/C Mothi Bagh Colony,Vikarabad,INDIA,soumithreddy.manchanpally@slu.edu,Y,9,21000,18150

In [46]:
sevis['Major_2_Code'].unique()

array([ 0.    , 26.1103, 11.0104, 11.0102, 51.1102, 11.0701, 52.1301,
       52.0211, 52.1101, 29.0207, 52.0201, 26.1309, 26.0101, 52.0203,
       11.0101])

In [47]:
#Export4 = sevis.to_excel("Sevis_Cleaned.xlsx", sheet_name = "Sevis", index = False)
#Export4

## Merging the four datasets

In [48]:
for df in [applicant, outreach]:
    df['Official_University_email_address'] = (
        df['Official_University_email_address']
        .astype(str)
        .str.strip()
        .str.lower()
    )

In [49]:
# Keep first occurrence only
applicant.drop_duplicates(subset='Reference_ID')
applicant.drop_duplicates(subset='Official_University_email_address')
outreach.drop_duplicates(subset='Official_University_email_address')

,Student_Full_Name,Program_Of_interest,Term,Application_Source,Global_Grad_Indicator,Deposit_Paid,Accepted_Admission,SEVIS_ID,I_20_In_Slate,Person_Email,Official_University_email_address,I_901_Status,Citizenship_(Primary),Application_Agency_Code,Contact_Number,Student_Status,Remarks
0,Chatarajupalli Dhruvakumar,Health Data Science (MS),Fall 2024,INTO,No,Yes,Yes,N0035601594,Yes,dhruvakumar1718@gmail.com,dhruvakumar.chatarajupalli@slu.edu,Payment,India,INTO SLU,7731891178,Visa approved,Not provided
1,Dachuri Harika,Information Systems (MS),Fall 2024,Slate,Yes,Yes,Yes,N0035617247,Yes,dachuriharika@gmail.com,harika.dachuri@slu.edu,Payment,India,GRC05,8008504742,Outreach efforts,Not interested in SLU
2,Pamidi Sravani,Information Systems (MS),Fall 2024,INTO,Yes,Yes,Yes,N0034926841,Yes,pamidisravani888@gmail.com,sravani.pamidi@slu.edu,Payment,India,INTO SLU,9390377842,Appointment schedule,Not provided
3,Lakshmi Venkata Subrahmanyam Parise,Information Systems (MS),Fall 2024,INTO,Yes,Yes,Yes,N0035409324,Yes,subrahmanyamparise2024@gmail.com,parise.lakshmivenkatasubrahmanyam@slu.edu,Payment,India,INTO SLU,9347915699,Visa denied,Not provided
4,Sarepalli Ben Jagadeesh,Supply Chain Management (MS),Fall 2024,INTO,Yes,Yes,Yes,N0035427864,Yes,sarepallibenjagadeesh@gmail.com,benjagadeesh.sarepalli@slu.edu,Payment,India,INTO SLU,9290688899,Visa approved,Not provided
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1560,"Reddy, Sai Divya (Reddy Sai Divya)",Health Data Science (MS),Fall 2024,Slate,No,No,Yes,N0035824113,Yes,saidivyareddyreddy2000@gmail.com,saidivyareddy.reddy@slu.edu,Payment,India,GRC01,9110349723,Outreach efforts,Email/whats'app sent
1561,"Lawal, Abideen (Olawale)",Business Administration (MBA),Fall 2024,Slate,Yes,No,Yes,N0035883932,Yes,m.abideenlawal@gmail.com,olawale.lawal@slu.edu,Payment,Nigeria,Others,995551532445,Outreach efforts,Email/whats'app sent
1562,"Erla, Sneha Latha",Information Systems (MS),Fall 2024,INTO,Yes,No,Yes,N0035949561,Yes,erlasneha1@gmail.com,snehalatha.erla@slu.edu,Payment,India,INTO SLU,9390185273,Outreach efforts,Email/whats'app sent
1563,"Tiwari, Sakshi",Anatomy (MS),Fall 2024,Slate,No,No,No,N0032269676,Yes,sakshitiwari3562@gmail.com,sakshi.tiwari.1@slu.edu,Payment,India,Others,No phone Number,Outreach efforts,Email/whats'app sent
1564,"Yathakula, William Cary",Information Systems (MS),Fall 2024,Slate,Yes,No,No,N0035974991,Yes,ywcary.07@gmail.com,williamcary.yathakula@slu.edu,Payment,India,GRC18,7337005451,Outreach efforts,Email/whats'app sent

In [ ]:
# Integating the 4 Datasets

Merged_dataset= pd.merge(applicant, connect,   on='Reference_ID', how='left', suffixes=('', '_connect'))

Merged_dataset_ = pd.merge(
    Merged_dataset,       
    sevis,      
    on='Official_University_email_address',     
    how='left', suffixes=('', '_sevis'),
    validate='many_to_one')

Merged_dataset_1 = pd.merge(
    Merged_dataset_,       
    outreach,   on='Official_University_email_address',     
    how='left', suffixes=('', '_outreach'),
    validate='many_to_one')

Merged_dataset_1

,Reference_ID,Given_Name,Last_Name,Departments,Received_At,University,Citizenship,Intake,Phone_Number,Street_1,...,Accepted_Admission,SEVIS_ID_outreach,I_20_In_Slate,Person_Email,I_901_Status,Citizenship_(Primary),Application_Agency_Code_outreach,Contact_Number,Student_Status,Remarks
0,1289258,Adekunle,Adefowoju,BusinessAdministration(MBA)ProfessionalMBA(Eve...,1970-01-01 00:29:04.630,Saint Louis University,Nigeria,Fall 2024,2350000000000,"9,HappinessEstateOffAmuleBusStopAyoboIpajaLago...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1294844,Emmanuel,AduNyarko,Analytics(MS)atSaintLouis,1970-01-01 00:29:04.630,Saint Louis University,Ghana,Fall 2024,233000000000,Plot11KwadwoAdjeistreet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1302877,Ogochukwu,Agina,Analytics(MS)atSaintLouis,1970-01-01 00:29:04.630,Saint Louis University,Nigeria,Fall 2024,2350000000000,DClose206Road,...,Yes,N0035085047,Yes,o.agina@gmail.com,Payment,Nigeria,Others,7037993011,Outreach efforts,Not connected
3,1299192,Afia,AgyapongAnsong,InformationSystems(MS)atSaintLouis,1970-01-01 00:29:04.630,Saint Louis University,Ghana,Fall 2024,234000000000,45NiiTsawest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1324269,RebeccaAgyeiwaa,Agyare,PublicHealth(MPH)EpidemiologyatSaintLouis,1970-01-01 00:29:04.630,Saint Louis University,Ghana,Fall 2024,234000000000,GbaweCConnieTaxiRank,...,Yes,N0035048639,Yes,rebeccaagyare67@gmail.com,Payment,Ghana,INTO SLU,233553468259,Visa approved,Not provided
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6888,1424285,Avinash,Jha,Cybersecurity (MS),1970-01-01 00:29:08.330,Saint Louis University,Nepal,Fall 2026,+977 981-7895320,Kadam Chowk -2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6889,1440172,Samuel Opeyemi,Olabintan,Biomedical Engineering (PHD),1970-01-01 00:29:08.330,Saint Louis University,Nigeria,Fall 2026,+234 701 908 6202,"28,Fabukade Street,Shogunle",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6890,1356764,Ama,Essel,Project Management (MS),1970-01-01 00:29:08.330,Saint Louis University,Ghana,Fall 2026,+233 24 808 6344,"C/O Jei River, Kasoa",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6891,1381727,Jonathan,Cobbina,Information Systems (MS),1970-01-01 00:29:08.330,Saint Louis University,Ghana,Fall 2026,+233 55 673 0711,CG0209-5667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6892,1439190,Paulinus,Daeli,Theological Studies (PHD),1970-01-01 00:29:08.330,Saint Louis University,Indonesia,Fall 2026,+1 623-283-7260,2850 Abbey Plz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
Merged_dataset_1.isna().sum()

Reference_ID                           0
Given_Name                             0
Last_Name                              0
Departments                            0
Received_At                            0
                                    ...
Citizenship_(Primary)               6419
Application_Agency_Code_outreach    6419
Contact_Number                      6419
Student_Status                      6419
Remarks                             6419
Length: 116, dtype: int64

In [52]:
Merged_dataset_1["Remarks"].unique()

array([nan, 'Not connected', 'Not provided', 'Waiting for slots',
       "Email/whats'app sent", 'Need call back', 'Want to defer'],
      dtype=object)

## Merged Cleaning and Manipulation

In [53]:
Merged_dataset_1.drop('Created_At_connect', axis= 1, inplace=True)
Merged_dataset_1.drop('Modified_At_connect', axis= 1, inplace=True)
Merged_dataset_1.drop('University_connect', axis= 1, inplace=True)
Merged_dataset_1.drop('SEVIS_ID_sevis', axis= 1, inplace=True)
Merged_dataset_1.drop('Country_of_Birth', axis= 1, inplace=True)
Merged_dataset_1.drop('Surname_Or_Primary_Name', axis= 1, inplace=True)
Merged_dataset_1.drop('Given_Name_sevis', axis= 1, inplace=True)
Merged_dataset_1.drop('Preferred_Name', axis= 1, inplace=True)
Merged_dataset_1.drop('Country_of_Citizenship', axis= 1, inplace=True)
Merged_dataset_1.drop('Application_Source_outreach', axis= 1, inplace=True)
Merged_dataset_1.drop('SEVIS_ID_outreach', axis= 1, inplace=True)

In [54]:
Merged_dataset_1.drop('SEVIS_Status', axis= 1, inplace=True)
Merged_dataset_1.drop('Class_of_Admission', axis= 1, inplace=True)
Merged_dataset_1.drop('Date_of_Birth_sevis', axis= 1, inplace=True)
Merged_dataset_1.drop('On-Campus_Employment', axis= 1, inplace=True)
Merged_dataset_1.drop('School_Code', axis= 1, inplace=True)
Merged_dataset_1.drop('Campus_Name', axis= 1, inplace=True)
Merged_dataset_1.drop('Campus_Code', axis= 1, inplace=True)

Merged_dataset_1.drop('Major_1_CIP_2020_Conversion', axis= 1, inplace=True)
Merged_dataset_1.drop('Major_2_Code', axis= 1, inplace=True)
Merged_dataset_1.drop('Major_2_CIP_2020_conversion', axis= 1, inplace=True)
Merged_dataset_1.drop('Minor_CIP_2020_Conversion', axis= 1, inplace=True)

Merged_dataset_1.drop('School_Requires_English_Proficiency', axis= 1, inplace=True)
Merged_dataset_1.drop('Student_Has_English_Proficiency', axis= 1, inplace=True)
Merged_dataset_1.drop('CPT_Approved', axis= 1, inplace=True)
Merged_dataset_1.drop('OCE_Requested', axis= 1, inplace=True)
Merged_dataset_1.drop('OCE_Approved', axis= 1, inplace=True)
Merged_dataset_1.drop('Pre-Completion_OPT_Requested', axis= 1, inplace=True)
Merged_dataset_1.drop('Pre-Completion_OPT_Approved', axis= 1, inplace=True)
Merged_dataset_1.drop('Post-Completion_OPT_Requested', axis= 1, inplace=True)

Merged_dataset_1.drop('Post-Completion_OPT_Approved', axis= 1, inplace=True)
Merged_dataset_1.drop('STEM_OPT_Requested', axis= 1, inplace=True)
Merged_dataset_1.drop('STEM_OPT_Approved', axis= 1, inplace=True)
Merged_dataset_1.drop('Cap_Gap_Extended', axis= 1, inplace=True)
Merged_dataset_1.drop('Student_Requested_Reinstatement', axis= 1, inplace=True)
Merged_dataset_1.drop('Student_Change_of_Status_Request', axis= 1, inplace=True)
Merged_dataset_1.drop('Student_Extension_Requested', axis= 1, inplace=True)
Merged_dataset_1.drop('Student_Authorized_to_Drop_Below_Full_Course_of_Study', axis= 1, inplace=True)
Merged_dataset_1.drop('Student_Transfer_Out', axis= 1, inplace=True)


Merged_dataset_1.drop('Border_Commuter_Student', axis= 1, inplace=True)
Merged_dataset_1.drop('Correction_Request_Pending', axis= 1, inplace=True)
Merged_dataset_1.drop('Student_Full_Name', axis= 1, inplace=True)
Merged_dataset_1.drop('I_20_In_Slate', axis= 1, inplace=True)
Merged_dataset_1.drop('Application_Agency_Code_outreach', axis= 1, inplace=True)
Merged_dataset_1.drop('Citizenship_(Primary)', axis= 1, inplace=True)

In [55]:
Merged_dataset_1['Deposit_Status'].fillna('Other', inplace=True)
Merged_dataset_1['Assigned'].fillna('Not_available', inplace=True)
Merged_dataset_1['NonImmigrant_ID'].fillna('Not_recorded', inplace=True)

m_d = Merged_dataset_1['Recieved_At'].mean()
Merged_dataset_1['Recieved_At']= Merged_dataset_1['Recieved_At'].fillna(m_d)

Merged_dataset_1['I_20_Status'].fillna('Other', inplace=True)

m_dd = Merged_dataset_1['Status_Change_Date'].mean()
Merged_dataset_1['Status_Change_Date']= Merged_dataset_1['Status_Change_Date'].fillna(m_dd)

Merged_dataset_1['Gender'].fillna('Other', inplace=True)
Merged_dataset_1['Foreign_Address_1'].fillna('Not_recorded', inplace=True)
Merged_dataset_1['Foreign_City'].fillna('Not_recorded', inplace=True)
Merged_dataset_1['Foreign_Country'].fillna('Not_available', inplace=True)
Merged_dataset_1["No_Phone_Indicator"].replace({"Y": "Yes", "N": 'No'}, inplace = True)
Merged_dataset_1['No_Phone_Indicator'].fillna('Other', inplace=True)
Merged_dataset_1['Number_of_Months_(for_funding)'].fillna('Other', inplace=True)

m_d_d = Merged_dataset_1['Tuition_Fees'].mean()
Merged_dataset_1['Tuition_Fees']= Merged_dataset_1['Tuition_Fees'].fillna(m_d_d)

m_d_d1 = Merged_dataset_1['Living_Expenses'].mean()
Merged_dataset_1['Living_Expenses']= Merged_dataset_1['Living_Expenses'].fillna(m_d_d1)

m_d_d2 = Merged_dataset_1['Dependent_Expenses'].mean()
Merged_dataset_1['Dependent_Expenses']= Merged_dataset_1['Dependent_Expenses'].fillna(m_d_d2)

m_d_d3 = Merged_dataset_1['Other_Costs'].mean()
Merged_dataset_1['Other_Costs']= Merged_dataset_1['Other_Costs'].fillna(m_d_d3)

m_d_d4 = Merged_dataset_1["Student's_Personal_Funds"].mean()
Merged_dataset_1["Student's_Personal_Funds"]= Merged_dataset_1["Student's_Personal_Funds"].fillna(m_d_d4)

m_d_d5 = Merged_dataset_1["Funds_From_This_School"].mean()
Merged_dataset_1["Funds_From_This_School"]= Merged_dataset_1["Funds_From_This_School"].fillna(m_d_d5)

Merged_dataset_1['School_Fund_Type'].fillna('Others', inplace=True)
Merged_dataset_1['Other_Source_Type'].fillna('Others', inplace=True)
Merged_dataset_1['School_Name'].fillna('Saint Louis University', inplace=True)
Merged_dataset_1['I_20_Issue_Reason'].fillna('Other', inplace=True)
Merged_dataset_1['Education_Level'].fillna('OTHER', inplace=True)
Merged_dataset_1['Major_1_Description'].fillna('Other', inplace=True)
Merged_dataset_1['Major_1_Code'].fillna('OTHER', inplace=True)

Merged_dataset_1['I-901_Transaction_Type'].fillna('Not_recorded', inplace=True)
Merged_dataset_1["I-901_Transaction_Type"].replace({"Others": "Not_recorded"}, inplace = True)

Merged_dataset_1['I-901_Fee_Payment_Receipt'].fillna('Unknown', inplace=True)
Merged_dataset_1['Overall_Remarks'].fillna('Not Provided', inplace=True)

Merged_dataset_1['OPT_Portal'].fillna('Other', inplace=True)
Merged_dataset_1["OPT_Portal"].replace({"Y": "Yes", 'N': 'No'}, inplace = True)

Merged_dataset_1['Program_Of_interest'].fillna('Other', inplace=True)
Merged_dataset_1['Term'].fillna('Other', inplace=True)
Merged_dataset_1['Global_Grad_Indicator'].fillna('Not_Recorded', inplace=True)
Merged_dataset_1['Deposit_Paid'].fillna('Not_Recorded', inplace=True)
Merged_dataset_1['Accepted_Admission'].fillna('Not_Recorded', inplace=True)

Merged_dataset_1['Person_Email'].fillna('Not_Recorded', inplace=True)
Merged_dataset_1['I_901_Status'].fillna('Other', inplace=True)
Merged_dataset_1['Contact_Number'].fillna('Not_Recorded', inplace=True)
Merged_dataset_1['Student_Status'].fillna('Other', inplace=True)
Merged_dataset_1['Remarks'].fillna('Other', inplace=True)
Merged_dataset_1["Remarks"].replace({"Not Provided": "Other"}, inplace = True)


m_d_d6 = Merged_dataset_1["Funds_From_Other_Sources"].mean()
Merged_dataset_1["Funds_From_Other_Sources"]= Merged_dataset_1["Funds_From_Other_Sources"].fillna(m_d_d6)

m_dd1 = Merged_dataset_1["Date_of_Last_Event"].mean()
Merged_dataset_1["Date_of_Last_Event"]= Merged_dataset_1["Date_of_Last_Event"].fillna(m_dd1)

m_dd2 = Merged_dataset_1["Program_Start_Date"].mean()
Merged_dataset_1["Program_Start_Date"]= Merged_dataset_1["Program_Start_Date"].fillna(m_dd2)

m_dd3 = Merged_dataset_1["Program_End_Date"].mean()
Merged_dataset_1["Program_End_Date"]= Merged_dataset_1["Program_End_Date"].fillna(m_dd3)

m_dd4 = Merged_dataset_1["Initial_Session_Start_Date"].mean()
Merged_dataset_1["Initial_Session_Start_Date"]= Merged_dataset_1["Initial_Session_Start_Date"].fillna(m_dd4)

m_dd5 = Merged_dataset_1["Current_Session_Start_Date"].mean()
Merged_dataset_1["Current_Session_Start_Date"]= Merged_dataset_1["Current_Session_Start_Date"].fillna(m_dd5)

m_dd6 = Merged_dataset_1["I-901_Transaction_Date"].mean()
Merged_dataset_1["I-901_Transaction_Date"]= Merged_dataset_1["I-901_Transaction_Date"].fillna(m_dd6)

m_dd7 = Merged_dataset_1["I-901_Transaction_Amount"].mean()
Merged_dataset_1["I-901_Transaction_Amount"]= Merged_dataset_1["I-901_Transaction_Amount"].fillna(m_dd7)

In [56]:
Merged_dataset_1.isna().sum()

Reference_ID      0
Given_Name        0
Last_Name         0
Departments       0
Received_At       0
                 ..
Person_Email      0
I_901_Status      0
Contact_Number    0
Student_Status    0
Remarks           0
Length: 71, dtype: int64

In [ ]:
#Export5 = Merged_dataset_1.to_excel("Merged_dataset.xlsx", sheet_name = "Sevis", index = False)
#Export5

In [58]:
#applicant['Official_University_email_address'].isin(sevis['Official_University_email_address']).value_counts()

In [59]:
applicant['Official_University_email_address'].isin(outreach['Official_University_email_address']).value_counts()

Official_University_email_address
False    6419
True      474
Name: count, dtype: int64