In [1]:
import pandas as pd

import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

# Applicant Dataset

In [2]:
df_original = pd.read_csv(r"C:\Users\DELL\OneDrive\Documents\My_Applicants_Cleaned.csv")
df_original

,Reference_ID,Given_Name,Last_Name,Major,Country,University,Citizenship,Intake,College_1st_Choice,Street_1,...,Date_of_Birth,Most_Recent_Released_Decision,Application_Source,Is_Global_Grad,SEVIS_ID,Official_University_email_address,Application_Agency_Code,Created_At_Cleaned,Modified_At_Cleaned,Received_At_Cleaned
0,1289258,Adekunle,Adefowoju,BusinessAdministration(MBA)ProfessionalMBA(Eve...,Nigeria,Saint Louis University,Nigeria,Fall 2024,Health Data Science (MS),"9,HappinessEstateOffAmuleBusStopAyoboIpajaLago...",...,NaN,NaN,ERXWebAPP,NaN,NaN,adekunle.adefowoju@slu.edu,NaN,14/04/2025,14/04/2025,14/04/2025
1,1294844,Emmanuel,AduNyarko,Analytics(MS)atSaintLouis,Ghana,Saint Louis University,Ghana,Fall 2024,Information Systems (MS),Plot11KwadwoAdjeistreet,...,NaN,NaN,ERXWebAPP,NaN,NaN,emmanuel.adunyarko@slu.edu,NaN,14/04/2025,14/04/2025,14/04/2025
2,1302877,Ogochukwu,Agina,Analytics(MS)atSaintLouis,Nigeria,Saint Louis University,Nigeria,Fall 2024,Computer Science (MS),DClose206Road,...,NaN,NaN,ERXWebAPP,NaN,NaN,ogochukwu.agina@slu.edu,NaN,14/04/2025,14/04/2025,14/04/2025
3,1299192,Afia,AgyapongAnsong,InformationSystems(MS)atSaintLouis,Ghana,Saint Louis University,Ghana,Fall 2024,Information Systems (MS),45NiiTsawest,...,NaN,NaN,ERXWebAPP,NaN,NaN,afia.agyapongansong@slu.edu,NaN,14/04/2025,14/04/2025,14/04/2025
4,1324269,RebeccaAgyeiwaa,Agyare,PublicHealth(MPH)EpidemiologyatSaintLouis,Ghana,Saint Louis University,Ghana,Fall 2024,Supply Chain Management (MS),GbaweCConnieTaxiRank,...,NaN,NaN,INTO,NaN,NaN,rebeccaagyeiwaa.agyare@slu.edu,NaN,14/04/2025,14/04/2025,14/04/2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6889,1424285,Avinash,Jha,Cybersecurity (MS),NaN,Saint Louis University,Nepal,Fall 2026,NaN,Kadam Chowk -2,...,17/09/1998,19/05/2025,Slate,Yes,NaN,NaN,NaN,27/05/2025,27/05/2025,27/05/2025
6890,1440172,Samuel Opeyemi,Olabintan,Biomedical Engineering (PHD),NaN,Saint Louis University,Nigeria,Fall 2026,NaN,"28,Fabukade Street,Shogunle",...,21/04/2002,05/08/2025,Slate,No,NaN,opeyemi.olabintan@slu.edu,NaN,27/05/2025,27/05/2025,27/05/2025
6891,1356764,Ama,Essel,Project Management (MS),NaN,Saint Louis University,Ghana,Fall 2026,NaN,"C/O Jei River, Kasoa",...,30/12/1996,23/05/2025,Slate,Yes,NaN,NaN,NaN,27/05/2025,27/05/2025,27/05/2025
6892,1381727,Jonathan,Cobbina,Information Systems (MS),NaN,Saint Louis University,Ghana,Fall 2026,NaN,CG0209-5667,...,26/12/1999,23/05/2025,Slate,Yes,NaN,NaN,NaN,27/05/2025,27/05/2025,27/05/2025
6893,1439190,Paulinus,Daeli,Theological Studies (PHD),NaN,Saint Louis University,Indonesia,Fall 2026,NaN,2850 Abbey Plz,...,20/02/1998,05/06/2025,Slate,No,NaN,paulinus.daeli@slu.edu,NaN,27/05/2025,27/05/2025,27/05/2025

In [3]:
df_copied = df_original

In [4]:
df_copied.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6894 entries, 0 to 6893
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Reference_ID                       6894 non-null   int64
 1   Given_Name                         6894 non-null   object
 2   Last_Name                          6894 non-null   object
 3   Major                              6893 non-null   object
 4   Country                            19 non-null     object
 5   University                         6894 non-null   object
 6   Citizenship                        6892 non-null   object
 7   Intake                             6894 non-null   object
 8   College_1st_Choice                 19 non-null     object
 9   Street_1                           6853 non-null   object
 10  Street_2                           1729 non-null   object
 11  Street_3                           63 non-null     object
 12  City                               6889 non-null   object
 13  Region                             6575 non-null   object
 14  Email_ID                           6894 non-null   object
 15  Date_of_Birth                      6875 non-null   object
 16  Most_Recent_Released_Decision      6748 non-null   object
 17  Application_Source                 6893 non-null   object
 18  Is_Global_Grad                     6875 non-null   object
 19  SEVIS_ID                           2606 non-null   object
 20  Official_University_email_address  6831 non-null   object
 21  Application_Agency_Code            2567 non-null   object
 22  Created_At_Cleaned                 6894 non-null   object
 23  Modified_At_Cleaned                6894 non-null   object
 24  Received_At_Cleaned                6894 non-null   object
dtypes: int64(1), object(24)
memory usage: 1.3+ MB

In [5]:
df_copied['Created_At_Cleaned'] = pd.to_datetime(df_copied['Created_At_Cleaned'])
df_copied['Modified_At_Cleaned'] = pd.to_datetime(df_copied['Modified_At_Cleaned'])
df_copied['Received_At_Cleaned'] = pd.to_datetime(df_copied['Received_At_Cleaned'])

In [6]:
df_copied['Date_of_Birth'] = pd.to_datetime(df_copied['Date_of_Birth'])

In [7]:
df_copied['Most_Recent_Released_Decision'] = pd.to_datetime(df_copied['Most_Recent_Released_Decision'])

In [8]:
df_copied.head(5)

,Reference_ID,Given_Name,Last_Name,Major,Country,University,Citizenship,Intake,College_1st_Choice,Street_1,...,Date_of_Birth,Most_Recent_Released_Decision,Application_Source,Is_Global_Grad,SEVIS_ID,Official_University_email_address,Application_Agency_Code,Created_At_Cleaned,Modified_At_Cleaned,Received_At_Cleaned
0,1289258,Adekunle,Adefowoju,BusinessAdministration(MBA)ProfessionalMBA(Eve...,Nigeria,Saint Louis University,Nigeria,Fall 2024,Health Data Science (MS),"9,HappinessEstateOffAmuleBusStopAyoboIpajaLago...",...,NaT,NaT,ERXWebAPP,NaN,NaN,adekunle.adefowoju@slu.edu,NaN,2025-04-14,2025-04-14,2025-04-14
1,1294844,Emmanuel,AduNyarko,Analytics(MS)atSaintLouis,Ghana,Saint Louis University,Ghana,Fall 2024,Information Systems (MS),Plot11KwadwoAdjeistreet,...,NaT,NaT,ERXWebAPP,NaN,NaN,emmanuel.adunyarko@slu.edu,NaN,2025-04-14,2025-04-14,2025-04-14
2,1302877,Ogochukwu,Agina,Analytics(MS)atSaintLouis,Nigeria,Saint Louis University,Nigeria,Fall 2024,Computer Science (MS),DClose206Road,...,NaT,NaT,ERXWebAPP,NaN,NaN,ogochukwu.agina@slu.edu,NaN,2025-04-14,2025-04-14,2025-04-14
3,1299192,Afia,AgyapongAnsong,InformationSystems(MS)atSaintLouis,Ghana,Saint Louis University,Ghana,Fall 2024,Information Systems (MS),45NiiTsawest,...,NaT,NaT,ERXWebAPP,NaN,NaN,afia.agyapongansong@slu.edu,NaN,2025-04-14,2025-04-14,2025-04-14
4,1324269,RebeccaAgyeiwaa,Agyare,PublicHealth(MPH)EpidemiologyatSaintLouis,Ghana,Saint Louis University,Ghana,Fall 2024,Supply Chain Management (MS),GbaweCConnieTaxiRank,...,NaT,NaT,INTO,NaN,NaN,rebeccaagyeiwaa.agyare@slu.edu,NaN,2025-04-14,2025-04-14,2025-04-14

In [9]:
df_copied.isna().sum()

Reference_ID                            0
Given_Name                              0
Last_Name                               0
Major                                   1
Country                              6875
University                              0
Citizenship                             2
Intake                                  0
College_1st_Choice                   6875
Street_1                               41
Street_2                             5165
Street_3                             6831
City                                    5
Region                                319
Email_ID                                0
Date_of_Birth                          19
Most_Recent_Released_Decision         146
Application_Source                      1
Is_Global_Grad                         19
SEVIS_ID                             4288
Official_University_email_address      63
Application_Agency_Code              4327
Created_At_Cleaned                      0
Modified_At_Cleaned                     0
Received_At_Cleaned                     0
dtype: int64

# Connect Dataset

In [10]:
df_original2 = pd.read_csv(r"C:\Users\DELL\OneDrive\Documents\My_Connect_Cleaned.csv")
df_copied2 = df_original2
df_copied2

,Reference_ID,Deposit_Status,Assigned,Recieved_At,University,I_20_Status,Created_At_Cleaned,Modified_At_Cleaned
0,1320577,Yes,"Anna Kluemke, Mounika Bhuvana Maheswari Krishn...",14/04/2025,Saint Louis University,Yes,19/02/2025,19/02/2025
1,1356800,Yes,"Catherine Donahue, Jorge Jesus Pena Cevallos",14/04/2025,Saint Louis University,Yes,19/02/2025,19/02/2025
2,1356915,Yes,Ryan Stoeckel,14/04/2025,Saint Louis University,Yes,19/02/2025,19/02/2025
3,1319991,Yes,"Anna Kluemke, Mounika Bhuvana Maheswari Krishn...",14/04/2025,Saint Louis University,Yes,19/02/2025,19/02/2025
4,1266321,Yes,"Naresh Dama, Catherine Donahue",14/04/2025,Saint Louis University,Yes,19/02/2025,19/02/2025
...,...,...,...,...,...,...,...,...
6870,1424285,No,NaN,27/05/2025,Saint Louis University,No,15/06/2025,15/06/2025
6871,1440172,No,NaN,27/05/2025,Saint Louis University,No,15/06/2025,15/06/2025
6872,1356764,No,NaN,27/05/2025,Saint Louis University,No,15/06/2025,15/06/2025
6873,1381727,No,NaN,27/05/2025,Saint Louis University,No,15/06/2025,15/06/2025
6874,1439190,No,Aliia Raitova,27/05/2025,Saint Louis University,No,15/06/2025,15/06/2025

In [11]:
df_copied2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6875 entries, 0 to 6874
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Reference_ID         6875 non-null   int64
 1   Deposit_Status       6875 non-null   object
 2   Assigned             2914 non-null   object
 3   Recieved_At          6875 non-null   object
 4   University           6875 non-null   object
 5   I_20_Status          6875 non-null   object
 6   Created_At_Cleaned   6875 non-null   object
 7   Modified_At_Cleaned  6875 non-null   object
dtypes: int64(1), object(7)
memory usage: 429.8+ KB

In [12]:
df_copied2['Created_At_Cleaned'] = pd.to_datetime(df_copied2['Created_At_Cleaned'])
df_copied2['Modified_At_Cleaned'] = pd.to_datetime(df_copied2['Modified_At_Cleaned'])
df_copied2['Recieved_At'] = pd.to_datetime(df_copied2['Recieved_At'])

In [13]:
df_copied2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6875 entries, 0 to 6874
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Reference_ID         6875 non-null   int64
 1   Deposit_Status       6875 non-null   object
 2   Assigned             2914 non-null   object
 3   Recieved_At          6875 non-null   datetime64[ns]
 4   University           6875 non-null   object
 5   I_20_Status          6875 non-null   object
 6   Created_At_Cleaned   6875 non-null   datetime64[ns]
 7   Modified_At_Cleaned  6875 non-null   datetime64[ns]
dtypes: datetime64[ns](3), int64(1), object(4)
memory usage: 429.8+ KB

# Outreach Dataset

In [14]:
df_original3 = pd.read_csv(r"C:\Users\DELL\OneDrive\Documents\My_Outreach_Cleaned.csv")
df_copied3 = df_original3
df_copied3

,Student_Full_Name,Program_Of_interest,Term,Application_Source,Global_Grad_Indicator,Deposit_Paid,Accepted_Admission,SEVIS_ID,I_20_In_Slate,Person_Email,Person_SLU_Email_Address,I_901_Status,Citizenship_(Primary),Application_Agency_Code,Contact_Number,Student_Status,Remarks,Appointment_Date
0,Chatarajupalli Dhruvakumar,Health Data Science (MS),Fall 2024,INTO,No,Yes,Yes,N0035601594,Yes,dhruvakumar1718@gmail.com,dhruvakumar.chatarajupalli@slu.edu,Payment,India,INTO SLU,7.731891e+09,Visa approved,NaN,NaN
1,Dachuri Harika,Information Systems (MS),Fall 2024,Slate,Yes,Yes,Yes,N0035617247,Yes,dachuriharika@gmail.com,harika.dachuri@slu.edu,Payment,India,GRC05,8.008505e+09,Outreach efforts,Not interested in SLU,NaN
2,Pamidi Sravani,Information Systems (MS),Fall 2024,INTO,Yes,Yes,Yes,N0034926841,Yes,pamidisravani888@gmail.com,sravani.pamidi@slu.edu,Payment,India,INTO SLU,9.390378e+09,Appointment schedule,NaN,22/07/2025
3,Lakshmi Venkata Subrahmanyam Parise,Information Systems (MS),Fall 2024,INTO,Yes,Yes,Yes,N0035409324,Yes,subrahmanyamparise2024@gmail.com,parise.lakshmivenkatasubrahmanyam@slu.edu,Payment,India,INTO SLU,9.347916e+09,Visa denied,NaN,NaN
4,Sarepalli Ben Jagadeesh,Supply Chain Management (MS),Fall 2024,INTO,Yes,Yes,Yes,N0035427864,Yes,sarepallibenjagadeesh@gmail.com,benjagadeesh.sarepalli@slu.edu,Payment,India,INTO SLU,9.290689e+09,Visa approved,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1560,"Reddy, Sai Divya (Reddy Sai Divya)",Health Data Science (MS),Fall 2024,Slate,No,No,Yes,N0035824113,Yes,saidivyareddyreddy2000@gmail.com,saidivyareddy.reddy@slu.edu,Payment,India,GRC01,9.110350e+09,Outreach efforts,Email/whats'app sent,NaN
1561,"Lawal, Abideen (Olawale)",Business Administration (MBA),Fall 2024,Slate,Yes,No,Yes,N0035883932,Yes,m.abideenlawal@gmail.com,olawale.lawal@slu.edu,Payment,Nigeria,NaN,9.960000e+11,Outreach efforts,Email/whats'app sent,NaN
1562,"Erla, Sneha Latha",Information Systems (MS),Fall 2024,INTO,Yes,No,Yes,N0035949561,Yes,erlasneha1@gmail.com,snehalatha.erla@slu.edu,Payment,India,INTO SLU,9.390185e+09,Outreach efforts,Email/whats'app sent,NaN
1563,"Tiwari, Sakshi",Anatomy (MS),Fall 2024,Slate,No,No,No,N0032269676,Yes,sakshitiwari3562@gmail.com,sakshi.tiwari.1@slu.edu,Payment,India,NaN,NaN,Outreach efforts,Email/whats'app sent,NaN
1564,"Yathakula, William Cary",Information Systems (MS),Fall 2024,Slate,Yes,No,No,N0035974991,Yes,ywcary.07@gmail.com,williamcary.yathakula@slu.edu,Payment,India,GRC18,7.337005e+09,Outreach efforts,Email/whats'app sent,NaN

In [15]:
df_copied3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1565 entries, 0 to 1564
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Student_Full_Name         1565 non-null   object
 1   Program_Of_interest       1565 non-null   object
 2   Term                      1565 non-null   object
 3   Application_Source        1565 non-null   object
 4   Global_Grad_Indicator     1565 non-null   object
 5   Deposit_Paid              1565 non-null   object
 6   Accepted_Admission        1565 non-null   object
 7   SEVIS_ID                  1565 non-null   object
 8   I_20_In_Slate             1565 non-null   object
 9   Person_Email              1565 non-null   object
 10  Person_SLU_Email_Address  1565 non-null   object
 11  I_901_Status              1565 non-null   object
 12  Citizenship_(Primary)     1565 non-null   object
 13  Application_Agency_Code   1221 non-null   object
 14  Contact_Number            1527 non-null   float64
 15  Student_Status            1565 non-null   object
 16  Remarks                   817 non-null    object
 17  Appointment_Date          287 non-null    object
dtypes: float64(1), object(17)
memory usage: 220.2+ KB

In [16]:
df_copied3['Appointment_Date'] = pd.to_datetime(df_copied3['Appointment_Date'])

In [17]:
df_copied3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1565 entries, 0 to 1564
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Student_Full_Name         1565 non-null   object
 1   Program_Of_interest       1565 non-null   object
 2   Term                      1565 non-null   object
 3   Application_Source        1565 non-null   object
 4   Global_Grad_Indicator     1565 non-null   object
 5   Deposit_Paid              1565 non-null   object
 6   Accepted_Admission        1565 non-null   object
 7   SEVIS_ID                  1565 non-null   object
 8   I_20_In_Slate             1565 non-null   object
 9   Person_Email              1565 non-null   object
 10  Person_SLU_Email_Address  1565 non-null   object
 11  I_901_Status              1565 non-null   object
 12  Citizenship_(Primary)     1565 non-null   object
 13  Application_Agency_Code   1221 non-null   object
 14  Contact_Number            1527 non-null   float64
 15  Student_Status            1565 non-null   object
 16  Remarks                   817 non-null    object
 17  Appointment_Date          287 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(16)
memory usage: 220.2+ KB

# Sevis Dataset

In [18]:
df_original4 = pd.read_csv(r"C:\Users\DELL\OneDrive\Documents\MY_Sevis_Cleaned.csv")
df_copied4 = df_original4
df_copied4

,SEVIS_ID,NonImmigrant_ID,FIN_ID,SEVIS_Status,Status_Change_Date,Class_of_Admission,Surname_Or_Primary_Name,Given_Name,Preferred_Name,Country_of_Birth,...,Program_End_Date,Initial_Session_Start_Date,Current_Session_Start_Date,School_Requires_English_Proficiency,Student_Has_English_Proficiency,I-901_Transaction_Type,I-901_Transaction_Date,I-901_Transaction_Amount,I-901_Fee_Payment_Receipt,Overall_Remarks
0,N0035966363,35966363,NaN,INITIAL,27/06/2024,F-1,Anya,Kelechi Amaechi,Kelechi Anya,NIGERIA,...,31/05/2026,21/08/2024,21/08/2024,Y,Y,Payment,20/11/2023,350.0,AAA2405170028,Student must report to university within 7 day...
1,N0036036214,36036214,NaN,INITIAL,23/07/2024,F-1,Kommareddy,Sunand Chowdary,Sunand Kommareddy,INDIA,...,31/05/2028,21/08/2024,21/08/2024,Y,Y,NaN,NaN,NaN,NaN,Student must report to university within 7 day...
2,N0035434583,35434583,NaN,INITIAL,21/03/2024,F-1,Siva,Mukesh,Mukesh,INDIA,...,31/05/2026,21/08/2024,21/08/2024,Y,Y,NaN,NaN,NaN,NaN,Student must report to university within 7 day...
3,N0035831856,35831856,NaN,INITIAL,28/05/2024,F-1,Palaparthi,Yehoshuva,Yehoshuva Palaparthi,INDIA,...,31/05/2026,21/08/2024,21/08/2024,Y,Y,Payment,12/07/2023,350.0,CCC2406895590,Student must report to university within 7 day...
4,N0035686561,35686561,NaN,INITIAL,05/02/2024,F-1,Manchanpally,Soumith Reddy,Soumith Reddy,INDIA,...,31/05/2026,21/08/2024,21/08/2024,Y,Y,NaN,NaN,NaN,NaN,Student must report to university within 7 day...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3847,N0035984560,35984560,NaN,INITIAL,07/03/2024,F-1,Bailapudi,Bhanu Satya Sireesha,Bhanu Satya Sireesha,INDIA,...,31/12/2026,21/08/2024,21/08/2024,Y,Y,NaN,NaN,NaN,NaN,Student must report to university within 7 day...
3848,N0035037716,35037716,NaN,INITIAL,11/10/2023,F-1,Komari,Chandana,Chandana,INDIA,...,31/05/2026,21/08/2024,16/01/2024,Y,Y,Payment,12/12/2023,350.0,CCC2407378561,Student must report to university within 7 day...
3849,N0035739381,35739381,NaN,INITIAL,05/10/2024,F-1,Chellappagarla Vijayakumar,Balaji,Balaji Chellappagarla Vijayakumar,INDIA,...,31/05/2026,21/08/2024,21/08/2024,Y,Y,NaN,NaN,NaN,NaN,Student must report to university within 7 day...
3850,N0035815054,35815054,NaN,INITIAL,23/05/2024,F-1,Bathina,Manichand,Manichand Bathina,INDIA,...,31/05/2026,21/08/2024,21/08/2024,Y,Y,Payment,13/06/2024,350.0,CCC2425794228,Student must report to university within 7 day...
3851,N0034960937,34960937,1.351418e+09,INITIAL,24/07/2024,F-1,Vegesna,Pavan Kumar Varma,Pavan,INDIA,...,31/05/2026,21/08/2024,21/08/2024,Y,Y,Payment,13/12/2023,350.0,CCC2407381223,Student must report to university within 7 day...

In [19]:
df_copied4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3852 entries, 0 to 3851
Data columns (total 83 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   SEVIS_ID                             3852 non-null   object
 1   NonImmigrant_ID                      3852 non-null   int64
 2   FIN_ID                               122 non-null    float64
 3   SEVIS_Status                         3852 non-null   object
 4   Status_Change_Date                   3852 non-null   object
 5   Class_of_Admission                   3852 non-null   object
 6   Surname_Or_Primary_Name              3852 non-null   object
 7   Given_Name                           3702 non-null   object
 8   Preferred_Name                       3852 non-null   object
 9   Country_of_Birth                     3852 non-null   object
 10  City_of_Birth                        90 non-null     object
 11  Date_of_Birth                        3851 non-null   object
 12  Country_of_Citizenship               3852 non-null   object
 13  Gender                               3852 non-null   object
 14  US_Physical_Address_Status           30 non-null     object
 15  US_Physical_Address_1                30 non-null     object
 16  US_Physical_City                     30 non-null     object
 17  US_Physical_State                    30 non-null     object
 18  US_Physical_Postal_Code              30 non-null     float64
 19  US_Physical_Routing_Code             13 non-null     float64
 20  US_Mailing_Address_Status            12 non-null     object
 21  US_Mailing_Address_1                 12 non-null     object
 22  US_Mailing_City                      12 non-null     object
 23  US_Mailing_State                     12 non-null     object
 24  US_Mailing_Postal_Code               12 non-null     float64
 25  US_Mailing_Routing_Code              1 non-null      float64
 26  Foreign_Address_1                    3852 non-null   object
 27  Foreign_Address_2                    1770 non-null   object
 28  Foreign_City                         3846 non-null   object
 29  Foreign_State_Province               213 non-null    object
 30  Foreign_Country                      3852 non-null   object
 31  Foreign_Postal_Code                  3148 non-null   object
 32  Email                                3848 non-null   object
 33  No_Phone_Indicator                   3851 non-null   object
 34  Foreign_Telephone_Country_Code       24 non-null     float64
 35  Foreign_Telephone                    24 non-null     float64
 36  Number_of_Months_(for_funding)       3852 non-null   int64
 37  Passport_Name                        9 non-null      object
 38  Passport_Number                      532 non-null    object
 39  Passport_Expiration_Date             120 non-null    object
 40  Passport_Country_of_Issuance         120 non-null    object
 41  Visa_Number                          531 non-null    object
 42  Visa_Issuance_Date                   525 non-null    object
 43  Visa_Expiration_Date                 524 non-null    object
 44  Visa_Issuance_Post                   377 non-null    object
 45  Port_of_Entry                        122 non-null    object
 46  Date_of_Entry                        122 non-null    object
 47  I_94_Admission_Number                105 non-null    object
 48  Port_of_Departure                    17 non-null     object
 49  Date_of_Departure                    17 non-null     object
 50  Tuition_Fees                         3852 non-null   int64
 51  Living_Expenses                      3852 non-null   int64
 52  Dependent_Expenses                   3840 non-null   float64
 53  Other_Costs                          3839 non-null   float64
 54  Other_Costs_Comment                  6 non-null      object
 55  Student's_Personal_Funds             3852 non-null   int64
 56  Funds_From_This_School               3849 non-null   float64
 57  School_Fund_Type                     3324 non-null   object
 58  Funds_From_Other_Sources             3846 non-null   float64
 59  Other_Source_Type                    3167 non-null   object
 60  On-Campus_Employment                 3836 non-null   float64
 61  Date_of_Last_Event                   3852 non-null   object
 62  School_Name                          3852 non-null   object
 63  School_Code                          3852 non-null   object
 64  Campus_Name                          3852 non-null   object
 65  Campus_Code                          3852 non-null   object
 66  I_20_Issue_Reason                    3852 non-null   object
 67  Education_Level                      3852 non-null   object
 68  Major_1_Code                         3852 non-null   float64
 69  Major_1_Description                  3852 non-null   object
 70  Major_2_Code                         3852 non-null   float64
 71  Major_2_Description                  32 non-null     object
 72  Program_Start_Date                   3852 non-null   object
 73  Program_End_Date                     3852 non-null   object
 74  Initial_Session_Start_Date           3852 non-null   object
 75  Current_Session_Start_Date           3852 non-null   object
 76  School_Requires_English_Proficiency  3852 non-null   object
 77  Student_Has_English_Proficiency      3850 non-null   object
 78  I-901_Transaction_Type               2108 non-null   object
 79  I-901_Transaction_Date               2108 non-null   object
 80  I-901_Transaction_Amount             2108 non-null   float64
 81  I-901_Fee_Payment_Receipt            2108 non-null   object
 82  Overall_Remarks                      3450 non-null   object
dtypes: float64(15), int64(5), object(63)
memory usage: 2.4+ MB

In [20]:
# Changing object to date format 

df_copied4['Status_Change_Date'] = pd.to_datetime(df_copied4['Status_Change_Date'])
df_copied4['Date_of_Birth'] = pd.to_datetime(df_copied4['Date_of_Birth'] )
df_copied4['Passport_Expiration_Date'] = pd.to_datetime(df_copied4['Passport_Expiration_Date'])
df_copied4['Visa_Issuance_Date'] = pd.to_datetime(df_copied4['Visa_Issuance_Date'])
df_copied4['Visa_Expiration_Date'] = pd.to_datetime(df_copied4['Visa_Expiration_Date'])
df_copied4['Date_of_Entry'] = pd.to_datetime(df_copied4['Date_of_Entry'])
#df_copied4['Date_of_Last_Event'] = pd.to_datetime(df_copied4['Date_of_Last_Event'])
#df_copied4['Program_Start_Date'] = pd.to_datetime(df_copied4['Program_Start_Date'])
df_copied4['Program_End_Date'] = pd.to_datetime(df_copied4['Program_End_Date'])
df_copied4['Initial_Session_Start_Date'] = pd.to_datetime(df_copied4['Initial_Session_Start_Date'])
df_copied4['Current_Session_Start_Date'] = pd.to_datetime(df_copied4['Current_Session_Start_Date'])
df_copied4['I-901_Transaction_Date'] = pd.to_datetime(df_copied4['I-901_Transaction_Date'])

In [21]:
df_copied4.drop('Foreign_Address_1', axis=1, inplace= True)

In [22]:
df_copied4.drop('Foreign_Address_2', axis=1, inplace= True)

# APPLICANTTTT

In [23]:
df_original_1 = pd.read_excel(r"C:\Users\DELL\Downloads\Applicant_Data.xlsx")
applicant = df_original_1
applicant.head(5)

,Reference_ID,Given_Name,Last_Name,Major,Country,Received_At,University,Citizenship,Intake,College_1st_Choice,...,Phone_Number_2,Admit_Date,Most_Recent_Released_Decision,Application_Source,Is_Global_Grad,SEVIS_ID,Official_University_email_address,Application_Agency_Code,Created_At,Modified_At
0,1289258,Adekunle,Adefowoju,BusinessAdministration(MBA)ProfessionalMBA(Eve...,Nigeria,1744630000000,Saint Louis University,Nigeria,Fall 2024,Health Data Science (MS),...,7067957137,NaN,NaN,ERXWebAPP,NaN,NaN,adekunle.adefowoju@slu.edu,NaN,1744630000000,1744630000000
1,1294844,Emmanuel,AduNyarko,Analytics(MS)atSaintLouis,Ghana,1744630000000,Saint Louis University,Ghana,Fall 2024,Information Systems (MS),...,233000000000,NaN,NaN,ERXWebAPP,NaN,NaN,emmanuel.adunyarko@slu.edu,NaN,1744630000000,1744630000000
2,1302877,Ogochukwu,Agina,Analytics(MS)atSaintLouis,Nigeria,1744630000000,Saint Louis University,Nigeria,Fall 2024,Computer Science (MS),...,7037993011,NaN,NaN,ERXWebAPP,NaN,NaN,ogochukwu.agina@slu.edu,NaN,1744630000000,1744630000000
3,1299192,Afia,AgyapongAnsong,InformationSystems(MS)atSaintLouis,Ghana,1744630000000,Saint Louis University,Ghana,Fall 2024,Information Systems (MS),...,234000000000,NaN,NaN,ERXWebAPP,NaN,NaN,afia.agyapongansong@slu.edu,NaN,1744630000000,1744630000000
4,1324269,RebeccaAgyeiwaa,Agyare,PublicHealth(MPH)EpidemiologyatSaintLouis,Ghana,1744630000000,Saint Louis University,Ghana,Fall 2024,Supply Chain Management (MS),...,NaN,NaN,NaN,INTO,NaN,NaN,rebeccaagyeiwaa.agyare@slu.edu,NaN,1744630000000,1744630000000

In [24]:
applicant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6894 entries, 0 to 6893
Data columns (total 30 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Reference_ID                       6894 non-null   int64
 1   Given_Name                         6894 non-null   object
 2   Last_Name                          6894 non-null   object
 3   Major                              6893 non-null   object
 4   Country                            19 non-null     object
 5   Received_At                        6894 non-null   int64
 6   University                         6894 non-null   object
 7   Citizenship                        6892 non-null   object
 8   Intake                             6894 non-null   object
 9   College_1st_Choice                 19 non-null     object
 10  Phone_Number                       6800 non-null   object
 11  Street_1                           6853 non-null   object
 12  Street_2                           1729 non-null   object
 13  Street_3                           63 non-null     object
 14  City                               6889 non-null   object
 15  Region                             6575 non-null   object
 16  Postal                             6396 non-null   object
 17  Email_ID                           6894 non-null   object
 18  Date_of_Birth                      6875 non-null   object
 19  Comments                           0 non-null      float64
 20  Phone_Number_2                     190 non-null    object
 21  Admit_Date                         0 non-null      float64
 22  Most_Recent_Released_Decision      6748 non-null   object
 23  Application_Source                 6893 non-null   object
 24  Is_Global_Grad                     6875 non-null   object
 25  SEVIS_ID                           2606 non-null   object
 26  Official_University_email_address  6831 non-null   object
 27  Application_Agency_Code            2567 non-null   object
 28  Created_At                         6894 non-null   int64
 29  Modified_At                        6894 non-null   int64
dtypes: float64(2), int64(4), object(24)
memory usage: 1.6+ MB

In [25]:
applicant.isna().sum()

Reference_ID                            0
Given_Name                              0
Last_Name                               0
Major                                   1
Country                              6875
Received_At                             0
University                              0
Citizenship                             2
Intake                                  0
College_1st_Choice                   6875
Phone_Number                           94
Street_1                               41
Street_2                             5165
Street_3                             6831
City                                    5
Region                                319
Postal                                498
Email_ID                                0
Date_of_Birth                          19
Comments                             6894
Phone_Number_2                       6704
Admit_Date                           6894
Most_Recent_Released_Decision         146
Application_Source                      1
Is_Global_Grad                         19
SEVIS_ID                             4288
Official_University_email_address      63
Application_Agency_Code              4327
Created_At                              0
Modified_At                             0
dtype: int64

In [26]:
applicant['Official_University_email_address'].unique()

array(['adekunle.adefowoju@slu.edu', 'emmanuel.adunyarko@slu.edu',
       'ogochukwu.agina@slu.edu', ..., 'amoohgyan.amoohgyan@slu.edu',
       'opeyemi.olabintan@slu.edu', 'paulinus.daeli@slu.edu'],
      shape=(6831,), dtype=object)

In [27]:
applicant.columns

Index(['Reference_ID', 'Given_Name', 'Last_Name', 'Major', 'Country',
       'Received_At', 'University', 'Citizenship', 'Intake',
       'College_1st_Choice', 'Phone_Number', 'Street_1', 'Street_2',
       'Street_3', 'City', 'Region', 'Postal', 'Email_ID', 'Date_of_Birth',
       'Comments', 'Phone_Number_2', 'Admit_Date',
       'Most_Recent_Released_Decision', 'Application_Source', 'Is_Global_Grad',
       'SEVIS_ID', 'Official_University_email_address',
       'Application_Agency_Code', 'Created_At', 'Modified_At'],
      dtype='object')

In [28]:
applicant.shape

(6894, 30)

#Data cleaning

In [29]:
applicant['Created_At'] = pd.to_datetime(applicant['Created_At'])
applicant['Modified_At'] = pd.to_datetime(applicant['Modified_At'])
applicant['Most_Recent_Released_Decision'] = pd.to_datetime(applicant['Most_Recent_Released_Decision'])
applicant['Received_At'] = pd.to_datetime(applicant['Received_At'])
applicant['Date_of_Birth'] = pd.to_datetime(applicant['Date_of_Birth'])

In [30]:
applicant['Major'].fillna('Others', inplace = True)

applicant.rename(columns = {"Major": "Departments"}, inplace = True) 

applicant['Citizenship'].fillna('Others', inplace = True)

applicant['Street_1'].fillna('Unknown', inplace= True)

applicant['City'].fillna('Others', inplace= True)

applicant['Region'].fillna('Others', inplace= True)

applicant['Postal'].fillna('Others', inplace= True)

mean_date = applicant['Date_of_Birth'].mean()
applicant['Date_of_Birth'] = applicant['Date_of_Birth'].fillna(mean_date)

meean_date = applicant['Most_Recent_Released_Decision'].mean()
applicant['Most_Recent_Released_Decision'] = applicant['Most_Recent_Released_Decision'].fillna(meean_date)

applicant['Is_Global_Grad'].fillna('Unknown', inplace= True)

applicant['SEVIS_ID'].fillna('Unknown', inplace= True)

applicant['Official_University_email_address'].fillna('Unknown', inplace= True)

applicant['Application_Agency_Code'].fillna('Others', inplace= True)

applicant['Application_Source'].fillna('Others', inplace= True)

applicant['Phone_Number'].fillna('No phone Number', inplace= True)

#Data Manipulation

In [31]:
applicant.drop('Country', axis= 1, inplace= True)

applicant.drop('College_1st_Choice', axis= 1, inplace= True)

applicant.drop('Street_2', axis= 1, inplace= True)

applicant.drop('Street_3', axis= 1, inplace= True)

applicant.drop ('Comments', axis= True, inplace= True)

applicant.drop ('Phone_Number_2', axis= True, inplace= True)

applicant.drop ('Admit_Date', axis= True, inplace= True)

In [32]:
from datetime import datetime
#today = pd.Timestamp('today')

applicant['Age'] = (datetime.today() - applicant['Date_of_Birth']).dt.days // 365

#today.year - applicant['Date_of_Birth'].dt.year -((today.month, today.day) < (applicant['Date_of_Birth'].dt.month, applicant['Date_of_Birth'].dt.day))

In [33]:
applicant.isna().sum()

Reference_ID                         0
Given_Name                           0
Last_Name                            0
Departments                          0
Received_At                          0
University                           0
Citizenship                          0
Intake                               0
Phone_Number                         0
Street_1                             0
City                                 0
Region                               0
Postal                               0
Email_ID                             0
Date_of_Birth                        0
Most_Recent_Released_Decision        0
Application_Source                   0
Is_Global_Grad                       0
SEVIS_ID                             0
Official_University_email_address    0
Application_Agency_Code              0
Created_At                           0
Modified_At                          0
Age                                  0
dtype: int64

In [72]:
applicant[applicant.duplicated(subset=['Reference_ID'])] #Shows duplicated rows
applicant = applicant.drop_duplicates(subset=['Reference_ID'])
applicant.shape

(6893, 24)

In [34]:
applicant.tail(10)

,Reference_ID,Given_Name,Last_Name,Departments,Received_At,University,Citizenship,Intake,Phone_Number,Street_1,...,Date_of_Birth,Most_Recent_Released_Decision,Application_Source,Is_Global_Grad,SEVIS_ID,Official_University_email_address,Application_Agency_Code,Created_At,Modified_At,Age
6884,1390060,Funke,Ojo,Project Management (MS),1970-01-01 00:29:08.330,Saint Louis University,Nigeria,Fall 2026,No phone Number,No 5 Adeyinka Okunade close,...,1985-12-18,2025-05-19,Slate,Yes,Unknown,Unknown,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,40
6885,1438361,Grace,Irobi,Family Therapy (MA),1970-01-01 00:29:08.330,Saint Louis University,Nigeria,Fall 2026,+234 817 195 6635,"Umuchimanwiri, Obazu-Mbieri, Mbaitolu Local Go...",...,1991-08-22,2025-01-05,Slate,No,Unknown,grace.irobi@health.slu.edu,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,34
6886,1448408,Yuqi,Chen,Educational Leadership (PHD),1970-01-01 00:29:08.330,Saint Louis University,China,Fall 2026,+1 314-410-9411,212 S Meramec Ave Apt 1302,...,2000-01-04,2025-03-04,Slate,No,Unknown,iris.chen@slu.edu,No,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,26
6887,1449162,Evelyn,Arthur-Kwegyir,Educational Leadership (PHD),1970-01-01 00:29:08.330,Saint Louis University,Ghana,Fall 2026,+233 24 792 9024,M 255 Rose Hips Street CI-01059732,...,1978-11-02,2025-05-23,Slate,No,Unknown,evelyn.arthurkwegyir@slu.edu,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,47
6888,1442373,Leonard,Amooh Gyan,Geographic Information Sciences (MS),1970-01-01 00:29:08.330,Saint Louis University,Ghana,Fall 2026,+233 20 343 1710,No. 7 Obaahemaa Ampa Street,...,1992-05-06,2025-04-22,Slate,No,Unknown,amoohgyan.amoohgyan@slu.edu,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,33
6889,1424285,Avinash,Jha,Cybersecurity (MS),1970-01-01 00:29:08.330,Saint Louis University,Nepal,Fall 2026,+977 981-7895320,Kadam Chowk -2,...,1998-09-17,2025-05-19,Slate,Yes,Unknown,Unknown,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,27
6890,1440172,Samuel Opeyemi,Olabintan,Biomedical Engineering (PHD),1970-01-01 00:29:08.330,Saint Louis University,Nigeria,Fall 2026,+234 701 908 6202,"28,Fabukade Street,Shogunle",...,2002-04-21,2025-08-05,Slate,No,Unknown,opeyemi.olabintan@slu.edu,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,23
6891,1356764,Ama,Essel,Project Management (MS),1970-01-01 00:29:08.330,Saint Louis University,Ghana,Fall 2026,+233 24 808 6344,"C/O Jei River, Kasoa",...,1996-12-30,2025-05-23,Slate,Yes,Unknown,Unknown,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,29
6892,1381727,Jonathan,Cobbina,Information Systems (MS),1970-01-01 00:29:08.330,Saint Louis University,Ghana,Fall 2026,+233 55 673 0711,CG0209-5667,...,1999-12-26,2025-05-23,Slate,Yes,Unknown,Unknown,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,26
6893,1439190,Paulinus,Daeli,Theological Studies (PHD),1970-01-01 00:29:08.330,Saint Louis University,Indonesia,Fall 2026,+1 623-283-7260,2850 Abbey Plz,...,1998-02-20,2025-06-05,Slate,No,Unknown,paulinus.daeli@slu.edu,Others,1970-01-01 00:29:08.330,1970-01-01 00:29:08.330,28

# CONNECTTTT

In [35]:
df_original_2 = pd.read_excel(r"C:\Users\DELL\Downloads\Connect.xlsx")
connect = df_original_2
connect.head(5)

,Reference_ID,Deposit_Status,Assigned,Recieved_At,University,I_20_Status,Created_At,Modified_At
0,1320577,Yes,"Anna Kluemke, Mounika Bhuvana Maheswari Krishn...",4/14/2025 19:55,Saint Louis University,Yes,1740000000000,1740000000000
1,1356800,Yes,"Catherine Donahue, Jorge Jesus Pena Cevallos",4/14/2025 19:55,Saint Louis University,Yes,1740000000000,1740000000000
2,1356915,Yes,Ryan Stoeckel,4/14/2025 19:55,Saint Louis University,Yes,1740000000000,1740000000000
3,1319991,Yes,"Anna Kluemke, Mounika Bhuvana Maheswari Krishn...",4/14/2025 19:55,Saint Louis University,Yes,1740000000000,1740000000000
4,1266321,Yes,"Naresh Dama, Catherine Donahue",4/14/2025 19:55,Saint Louis University,Yes,1740000000000,1740000000000

In [36]:
connect.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34341 entries, 0 to 34340
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Reference_ID    34341 non-null  int64
 1   Deposit_Status  34341 non-null  object
 2   Assigned        14531 non-null  object
 3   Recieved_At     34341 non-null  object
 4   University      34341 non-null  object
 5   I_20_Status     34341 non-null  object
 6   Created_At      34341 non-null  int64
 7   Modified_At     34341 non-null  int64
dtypes: int64(3), object(5)
memory usage: 2.1+ MB

In [37]:
connect.isna().sum()

Reference_ID          0
Deposit_Status        0
Assigned          19810
Recieved_At           0
University            0
I_20_Status           0
Created_At            0
Modified_At           0
dtype: int64

In [38]:
connect['Recieved_At'] = pd.to_datetime(connect['Recieved_At'])

In [39]:
connect['Assigned'].fillna('Others', inplace= True)

In [68]:
connect[connect.duplicated(subset=['Reference_ID'])] #Shows duplicated rows
connect = connect.drop_duplicates(subset=['Reference_ID'])

In [40]:
connect.isna().sum()

Reference_ID      0
Deposit_Status    0
Assigned          0
Recieved_At       0
University        0
I_20_Status       0
Created_At        0
Modified_At       0
dtype: int64

In [69]:
connect.shape

(6875, 8)

# OUTREACHHHH

In [41]:
df_original_3 = pd.read_excel(r"C:\Users\DELL\Downloads\Outreach_Data.xlsx")
outreach = df_original_3
outreach.head(5)

,Student_Full_Name,Program_Of_interest,Term,Application_Source,Global_Grad_Indicator,Deposit_Paid,Accepted_Admission,SEVIS_ID,I_20_In_Slate,Person_Email,Person_SLU_Email_Address,I_901_Status,Citizenship_(Primary),Application_Agency_Code,Contact_Number,Student_Status,Remarks,Appointment_Date
0,Chatarajupalli Dhruvakumar,Health Data Science (MS),Fall 2024,INTO,No,Yes,Yes,N0035601594,Yes,dhruvakumar1718@gmail.com,dhruvakumar.chatarajupalli@slu.edu,Payment,India,INTO SLU,7731891178,Visa approved,NaN,NaN
1,Dachuri Harika,Information Systems (MS),Fall 2024,Slate,Yes,Yes,Yes,N0035617247,Yes,dachuriharika@gmail.com,harika.dachuri@slu.edu,Payment,India,GRC05,8008504742,Outreach efforts,Not interested in SLU,NaN
2,Pamidi Sravani,Information Systems (MS),Fall 2024,INTO,Yes,Yes,Yes,N0034926841,Yes,pamidisravani888@gmail.com,sravani.pamidi@slu.edu,Payment,India,INTO SLU,9390377842,Appointment schedule,NaN,2025-07-22 00:00:00
3,Lakshmi Venkata Subrahmanyam Parise,Information Systems (MS),Fall 2024,INTO,Yes,Yes,Yes,N0035409324,Yes,subrahmanyamparise2024@gmail.com,parise.lakshmivenkatasubrahmanyam@slu.edu,Payment,India,INTO SLU,9347915699,Visa denied,NaN,NaN
4,Sarepalli Ben Jagadeesh,Supply Chain Management (MS),Fall 2024,INTO,Yes,Yes,Yes,N0035427864,Yes,sarepallibenjagadeesh@gmail.com,benjagadeesh.sarepalli@slu.edu,Payment,India,INTO SLU,9290688899,Visa approved,NaN,NaN

In [42]:
outreach.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1565 entries, 0 to 1564
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Student_Full_Name         1565 non-null   object
 1   Program_Of_interest       1565 non-null   object
 2   Term                      1565 non-null   object
 3   Application_Source        1565 non-null   object
 4   Global_Grad_Indicator     1565 non-null   object
 5   Deposit_Paid              1565 non-null   object
 6   Accepted_Admission        1565 non-null   object
 7   SEVIS_ID                  1565 non-null   object
 8   I_20_In_Slate             1565 non-null   object
 9   Person_Email              1565 non-null   object
 10  Person_SLU_Email_Address  1565 non-null   object
 11  I_901_Status              1565 non-null   object
 12  Citizenship_(Primary)     1565 non-null   object
 13  Application_Agency_Code   1221 non-null   object
 14  Contact_Number            1531 non-null   object
 15  Student_Status            1565 non-null   object
 16  Remarks                   817 non-null    object
 17  Appointment_Date          373 non-null    object
dtypes: object(18)
memory usage: 220.2+ KB

In [43]:
outreach['Person_Email'].unique()

array(['dhruvakumar1718@gmail.com', 'dachuriharika@gmail.com',
       'pamidisravani888@gmail.com', ..., 'erlasneha1@gmail.com',
       'sakshitiwari3562@gmail.com', 'ywcary.07@gmail.com'],
      shape=(1560,), dtype=object)

In [44]:
outreach.isna().sum()

Student_Full_Name              0
Program_Of_interest            0
Term                           0
Application_Source             0
Global_Grad_Indicator          0
Deposit_Paid                   0
Accepted_Admission             0
SEVIS_ID                       0
I_20_In_Slate                  0
Person_Email                   0
Person_SLU_Email_Address       0
I_901_Status                   0
Citizenship_(Primary)          0
Application_Agency_Code      344
Contact_Number                34
Student_Status                 0
Remarks                      748
Appointment_Date            1192
dtype: int64

In [45]:
outreach.rename(columns = {"Person_SLU_Email_Address": "Official_University_email_address"}, inplace = True) 

outreach['Contact_Number'].fillna('No phone Number', inplace= True)

outreach['Application_Agency_Code'].fillna('Others', inplace=True)

outreach['Remarks'].fillna('Not provided', inplace= True)

In [46]:
outreach.drop('Appointment_Date', axis= 1, inplace= True)

In [75]:
outreach[outreach.duplicated(subset=['Official_University_email_address'])] #Shows duplicated rows
outreach = outreach.drop_duplicates(subset=['Official_University_email_address'])
outreach.shape

(1560, 17)

In [47]:
outreach.isna().sum()

Student_Full_Name                    0
Program_Of_interest                  0
Term                                 0
Application_Source                   0
Global_Grad_Indicator                0
Deposit_Paid                         0
Accepted_Admission                   0
SEVIS_ID                             0
I_20_In_Slate                        0
Person_Email                         0
Official_University_email_address    0
I_901_Status                         0
Citizenship_(Primary)                0
Application_Agency_Code              0
Contact_Number                       0
Student_Status                       0
Remarks                              0
dtype: int64

In [48]:
outreach.head(5)

,Student_Full_Name,Program_Of_interest,Term,Application_Source,Global_Grad_Indicator,Deposit_Paid,Accepted_Admission,SEVIS_ID,I_20_In_Slate,Person_Email,Official_University_email_address,I_901_Status,Citizenship_(Primary),Application_Agency_Code,Contact_Number,Student_Status,Remarks
0,Chatarajupalli Dhruvakumar,Health Data Science (MS),Fall 2024,INTO,No,Yes,Yes,N0035601594,Yes,dhruvakumar1718@gmail.com,dhruvakumar.chatarajupalli@slu.edu,Payment,India,INTO SLU,7731891178,Visa approved,Not provided
1,Dachuri Harika,Information Systems (MS),Fall 2024,Slate,Yes,Yes,Yes,N0035617247,Yes,dachuriharika@gmail.com,harika.dachuri@slu.edu,Payment,India,GRC05,8008504742,Outreach efforts,Not interested in SLU
2,Pamidi Sravani,Information Systems (MS),Fall 2024,INTO,Yes,Yes,Yes,N0034926841,Yes,pamidisravani888@gmail.com,sravani.pamidi@slu.edu,Payment,India,INTO SLU,9390377842,Appointment schedule,Not provided
3,Lakshmi Venkata Subrahmanyam Parise,Information Systems (MS),Fall 2024,INTO,Yes,Yes,Yes,N0035409324,Yes,subrahmanyamparise2024@gmail.com,parise.lakshmivenkatasubrahmanyam@slu.edu,Payment,India,INTO SLU,9347915699,Visa denied,Not provided
4,Sarepalli Ben Jagadeesh,Supply Chain Management (MS),Fall 2024,INTO,Yes,Yes,Yes,N0035427864,Yes,sarepallibenjagadeesh@gmail.com,benjagadeesh.sarepalli@slu.edu,Payment,India,INTO SLU,9290688899,Visa approved,Not provided

# SEVISSS

In [49]:
df_original_4 = pd.read_excel(r"C:\Users\DELL\Downloads\SEVIS.xlsx")
sevis = df_original_4
sevis.head(5)

,SEVIS_ID,NonImmigrant_ID,FIN_ID,SEVIS_Status,Status_Change_Date,Class_of_Admission,Surname_Or_Primary_Name,Given_Name,Suffix,Preferred_Name,...,I-901_Transaction_Type,I-901_Transaction_Date,I-901_Transaction_Amount,I-901_Fee_Payment_Receipt,Border_Commuter_Student,Correction_Request_Pending,Cancellation_Reason,Overall_Remarks,Length_of_Next_Break_of_Vacation,OPT_Portal
0,N0035966363,35966363,NaN,INITIAL,6/27/2024,F-1,Anya,Kelechi Amaechi,NaN,Kelechi Anya,...,Payment,11/20/2023,350.0,AAA2405170028,N,N,NaN,Student must report to university within 7 day...,0,N
1,N0036036214,36036214,NaN,INITIAL,7/23/2024,F-1,Kommareddy,Sunand Chowdary,NaN,Sunand Kommareddy,...,NaN,NaN,NaN,NaN,N,N,NaN,Student must report to university within 7 day...,0,N
2,N0035434583,35434583,NaN,INITIAL,3/21/2024,F-1,Siva,Mukesh,NaN,Mukesh,...,NaN,NaN,NaN,NaN,N,N,NaN,Student must report to university within 7 day...,0,N
3,N0035831856,35831856,NaN,INITIAL,5/28/2024,F-1,Palaparthi,Yehoshuva,NaN,Yehoshuva Palaparthi,...,Payment,2023-07-12 00:00:00,350.0,CCC2406895590,N,N,NaN,Student must report to university within 7 day...,0,N
4,N0035686561,35686561,NaN,INITIAL,2024-02-05 00:00:00,F-1,Manchanpally,Soumith Reddy,NaN,Soumith Reddy,...,NaN,NaN,NaN,NaN,N,N,NaN,Student must report to university within 7 day...,0,N

In [50]:
sevis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3852 entries, 0 to 3851
Columns: 123 entries, SEVIS_ID to OPT_Portal
dtypes: float64(30), int64(7), object(86)
memory usage: 3.6+ MB

In [51]:
sevis['Length_of_Next_Break_of_Vacation'].unique()

array([0])

In [52]:
sevis.shape

(3852, 123)

In [53]:
sevis.iloc[:, :20].isna().sum()

SEVIS_ID                         0
NonImmigrant_ID                  0
FIN_ID                        3730
SEVIS_Status                     0
Status_Change_Date               0
Class_of_Admission               0
Surname_Or_Primary_Name          0
Given_Name                     150
Suffix                        3852
Preferred_Name                   0
SEVIS_Legacy_First_Name       3852
SEVIS_Legacy_Middle_Name      3852
SEVIS_Legacy_Last_Name        3852
Country_of_Birth                 0
City_of_Birth                 3762
Date_of_Birth                    1
Country_of_Citizenship           0
Gender                           0
US_Physical_Address_Status    3822
US_Physical_Address_1         3822
dtype: int64

In [54]:
sevis['Status_Change_Date'] = pd.to_datetime(sevis['Status_Change_Date'])
sevis['Date_of_Birth'] = pd.to_datetime(sevis['Date_of_Birth'])

sevis['I-901_Transaction_Date'] = pd.to_datetime(sevis['I-901_Transaction_Date'])
sevis['Date_of_Last_Event'] = pd.to_datetime(sevis['Date_of_Last_Event'])
sevis['Program_Start_Date'] = pd.to_datetime(sevis['Program_Start_Date'])
sevis['Program_End_Date'] = pd.to_datetime(sevis['Program_End_Date'])
sevis['Initial_Session_Start_Date'] = pd.to_datetime(sevis['Initial_Session_Start_Date'])
sevis['Current_Session_Start_Date'] = pd.to_datetime(sevis['Current_Session_Start_Date'])

sevis.rename(columns = {"Email": "Official_University_email_address"}, inplace = True)

In [57]:
sevis['Given_Name'].fillna('Not Provided', inplace=True)
sevis['Foreign_City'].fillna('Others', inplace=True)
sevis['Official_University_email_address'].fillna('Not Provided', inplace=True)
sevis['No_Phone_Indicator'].fillna('Not Provided', inplace=True)
sevis['Dependent_Expenses'].fillna(sevis['Dependent_Expenses'].mean(), inplace=True)
sevis['Other_Costs'].fillna(sevis['Other_Costs'].mean(), inplace=True)
sevis['Funds_From_This_School'].fillna(sevis['Funds_From_This_School'].mean(), inplace=True)
sevis['School_Fund_Type'].fillna('Others', inplace=True)
sevis['Funds_From_Other_Sources'].fillna(sevis['Funds_From_Other_Sources'].mean(), inplace=True)
sevis['Other_Source_Type'].fillna('Others', inplace=True)
sevis['On-Campus_Employment'].fillna(sevis['On-Campus_Employment'].mean(), inplace=True)
sevis['Student_Has_English_Proficiency'].fillna('Unknown', inplace=True)
sevis['I-901_Transaction_Type'].fillna('Others', inplace=True)
meeaan_date = sevis['I-901_Transaction_Date'].mean()
sevis['I-901_Transaction_Date'] = sevis['I-901_Transaction_Date'].fillna(meeaan_date)
meann_date = sevis['Date_of_Birth'].mean()
sevis['Date_of_Birth'] = sevis['Date_of_Birth'].fillna(meann_date)
sevis['I-901_Transaction_Amount'].fillna(sevis['I-901_Transaction_Amount'].mean(), inplace=True)
sevis['I-901_Fee_Payment_Receipt'].fillna('Unknown', inplace=True)
sevis['Overall_Remarks'].fillna('Not Provided', inplace=True)
sevis['Border_Commuter_Student'].fillna('Others', inplace=True)

In [ ]:
# Replacing values in a column
#sevis["PartTimeJob"].replace({"Yes": 1, "No": 0}, inplace = True)

In [58]:
sevis.drop('FIN_ID', axis= 1, inplace=True)
sevis.drop('Suffix', axis= 1, inplace=True)
sevis.drop('SEVIS_Legacy_First_Name', axis= 1, inplace=True)
sevis.drop('SEVIS_Legacy_Middle_Name', axis= 1, inplace=True)
sevis.drop('SEVIS_Legacy_Last_Name', axis= 1, inplace=True)
sevis.drop('City_of_Birth', axis= 1, inplace=True)
sevis.drop('US_Physical_Address_Status', axis= 1, inplace=True)
sevis.drop('US_Physical_Address_1', axis= 1, inplace=True)
sevis.drop('US_Physical_Address_2', axis= 1, inplace=True)

sevis.drop('US_Physical_City', axis= 1, inplace=True)
sevis.drop('US_Physical_State', axis= 1, inplace=True)
sevis.drop('US_Physical_Postal_Code', axis= 1, inplace=True)
sevis.drop('US_Physical_Routing_Code', axis= 1, inplace=True)
sevis.drop('US_Mailing_Address_Status', axis= 1, inplace=True)
sevis.drop('US_Mailing_Address_1', axis= 1, inplace=True)
sevis.drop('US_Mailing_Address_2', axis= 1, inplace=True)
sevis.drop('US_Mailing_City', axis= 1, inplace=True)

sevis.drop('US_Mailing_State', axis= 1, inplace=True)
sevis.drop('US_Mailing_Postal_Code', axis= 1, inplace=True)
sevis.drop('US_Mailing_Routing_Code', axis= 1, inplace=True)
sevis.drop('Foreign_Address_2', axis= 1, inplace=True)
sevis.drop('Foreign_State_Province', axis= 1, inplace=True)
sevis.drop('Foreign_Postal_Code', axis= 1, inplace=True)
sevis.drop('US_Telephone', axis= 1, inplace=True)

sevis.drop('Foreign_Telephone_Country_Code', axis= 1, inplace=True)
sevis.drop('Foreign_Telephone', axis= 1, inplace=True)
sevis.drop('Passport_Name', axis= 1, inplace=True)
sevis.drop('Passport_Number', axis= 1, inplace=True)
sevis.drop('Passport_Expiration_Date', axis= 1, inplace=True)
sevis.drop('Passport_Country_of_Issuance', axis= 1, inplace=True)
sevis.drop('Visa_Number', axis= 1, inplace=True)
sevis.drop('Visa_Issuance_Date', axis= 1, inplace=True)

sevis.drop('Visa_Expiration_Date', axis= 1, inplace=True)
sevis.drop('Visa_Issuance_Post', axis= 1, inplace=True)
sevis.drop('Port_of_Entry', axis= 1, inplace=True)
sevis.drop('Date_of_Entry', axis= 1, inplace=True)
sevis.drop('I_94_Admission_Number', axis= 1, inplace=True)
sevis.drop('Port_of_Departure', axis= 1, inplace=True)
sevis.drop('Date_of_Departure', axis= 1, inplace=True)
sevis.drop('Other_Costs_Comment', axis= 1, inplace=True)

sevis.drop('Cancellation_Reason', axis= 1, inplace=True)
sevis.drop('Termination_Reason', axis= 1, inplace=True)
sevis.drop('Other_Termination_Comment', axis= 1, inplace=True)
sevis.drop('Major_2_Description', axis= 1, inplace=True)
sevis.drop('Minor_Description', axis= 1, inplace=True)
sevis.drop('Current_Session_End_Date', axis= 1, inplace=True)
sevis.drop('Next_Session_Start_Date', axis= 1, inplace=True)
sevis.drop('Last_Session', axis= 1, inplace=True)
sevis.drop('Study_Research_Abroad', axis= 1, inplace=True)
sevis.drop('Thesis_Or_Dissertation', axis= 1, inplace=True)
sevis.drop('English_Is_Not_Required_Because', axis= 1, inplace=True)
sevis.drop('Length_of_Next_Break_of_Vacation', axis= 1, inplace=True)
sevis.drop('Minor_Code', axis= 1, inplace=True)

In [78]:
sevis[sevis.duplicated(subset=['Official_University_email_address'])] #Shows duplicated rows
sevis = sevis.drop_duplicates(subset=['Official_University_email_address'])
sevis.shape

(3837, 70)

In [ ]:
sevis.iloc[:, :20].head(5)

,SEVIS_ID,NonImmigrant_ID,SEVIS_Status,Status_Change_Date,Class_of_Admission,Surname_Or_Primary_Name,Given_Name,Preferred_Name,Country_of_Birth,Date_of_Birth,Country_of_Citizenship,Gender,Foreign_Address_1,Foreign_City,Foreign_Country,Email,No_Phone_Indicator,Number_of_Months_(for_funding),Tuition_Fees,Living_Expenses
0,N0035966363,35966363,INITIAL,2024-06-27,F-1,Anya,Kelechi Amaechi,Kelechi Anya,NIGERIA,1995-01-26,NIGERIA,FEMALE,"32, Samuel Street, Akowonjo road, Egbeda",Lagos,NIGERIA,kelechi.anya@slu.edu,Y,9,21000,18150
1,N0036036214,36036214,INITIAL,2024-07-23,F-1,Kommareddy,Sunand Chowdary,Sunand Kommareddy,INDIA,2005-10-16,INDIA,MALE,"5-1-84/7/402, GKS Arunodaya enclave",Medchal,INDIA,sunand.kommareddy@slu.edu,Y,9,55614,21350
2,N0035434583,35434583,INITIAL,2024-03-21,F-1,Siva,Mukesh,Mukesh,INDIA,2003-07-31,INDIA,MALE,No 1 lakshmi amml street,Chennai,INDIA,mukesh.siva@slu.edu,Y,9,21000,18150
3,N0035831856,35831856,INITIAL,2024-05-28,F-1,Palaparthi,Yehoshuva,Yehoshuva Palaparthi,INDIA,2002-08-18,INDIA,MALE,"D No: 1-36B, Ramayapalem Addanki",Bapatla,INDIA,yehoshuva.palaparthi@slu.edu,Y,9,21000,18150
4,N0035686561,35686561,INITIAL,2024-02-05,F-1,Manchanpally,Soumith Reddy,Soumith Reddy,INDIA,2002-04-19,INDIA,MALE,4-2-207/C Mothi Bagh Colony,Vikarabad,INDIA,soumithreddy.manchanpally@slu.edu,Y,9,21000,18150

In [ ]:
sevis['Major_2_Code'].unique()

array([ 0.    , 26.1103, 11.0104, 11.0102, 51.1102, 11.0701, 52.1301,
       52.0211, 52.1101, 29.0207, 52.0201, 26.1309, 26.0101, 52.0203,
       11.0101])

In [105]:
# Merging the four datasets

Merged_dataset= pd.merge(applicant, connect,   on='Reference_ID', how='left', suffixes=('', '_connect'))
Merged_dataset_ = pd.merge(Merged_dataset,       sevis,      on='Official_University_email_address',     how='left', suffixes=('', '_sevis'))
Merged_dataset_1 = pd.merge(Merged_dataset_,       outreach,   on='Official_University_email_address',     how='left', suffixes=('', '_outreach'))

Merged_dataset_1

,Reference_ID,Given_Name,Last_Name,Departments,Received_At,University,Citizenship,Intake,Phone_Number,Street_1,...,Accepted_Admission,SEVIS_ID_outreach,I_20_In_Slate,Person_Email,I_901_Status,Citizenship_(Primary),Application_Agency_Code_outreach,Contact_Number,Student_Status,Remarks
0,1289258,Adekunle,Adefowoju,BusinessAdministration(MBA)ProfessionalMBA(Eve...,1970-01-01 00:29:04.630,Saint Louis University,Nigeria,Fall 2024,2350000000000,"9,HappinessEstateOffAmuleBusStopAyoboIpajaLago...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1294844,Emmanuel,AduNyarko,Analytics(MS)atSaintLouis,1970-01-01 00:29:04.630,Saint Louis University,Ghana,Fall 2024,233000000000,Plot11KwadwoAdjeistreet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1302877,Ogochukwu,Agina,Analytics(MS)atSaintLouis,1970-01-01 00:29:04.630,Saint Louis University,Nigeria,Fall 2024,2350000000000,DClose206Road,...,Yes,N0035085047,Yes,o.agina@gmail.com,Payment,Nigeria,Others,7037993011,Outreach efforts,Not connected
3,1299192,Afia,AgyapongAnsong,InformationSystems(MS)atSaintLouis,1970-01-01 00:29:04.630,Saint Louis University,Ghana,Fall 2024,234000000000,45NiiTsawest,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1324269,RebeccaAgyeiwaa,Agyare,PublicHealth(MPH)EpidemiologyatSaintLouis,1970-01-01 00:29:04.630,Saint Louis University,Ghana,Fall 2024,234000000000,GbaweCConnieTaxiRank,...,Yes,N0035048639,Yes,rebeccaagyare67@gmail.com,Payment,Ghana,INTO SLU,233553468259,Visa approved,Not provided
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6888,1424285,Avinash,Jha,Cybersecurity (MS),1970-01-01 00:29:08.330,Saint Louis University,Nepal,Fall 2026,+977 981-7895320,Kadam Chowk -2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6889,1440172,Samuel Opeyemi,Olabintan,Biomedical Engineering (PHD),1970-01-01 00:29:08.330,Saint Louis University,Nigeria,Fall 2026,+234 701 908 6202,"28,Fabukade Street,Shogunle",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6890,1356764,Ama,Essel,Project Management (MS),1970-01-01 00:29:08.330,Saint Louis University,Ghana,Fall 2026,+233 24 808 6344,"C/O Jei River, Kasoa",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6891,1381727,Jonathan,Cobbina,Information Systems (MS),1970-01-01 00:29:08.330,Saint Louis University,Ghana,Fall 2026,+233 55 673 0711,CG0209-5667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6892,1439190,Paulinus,Daeli,Theological Studies (PHD),1970-01-01 00:29:08.330,Saint Louis University,Indonesia,Fall 2026,+1 623-283-7260,2850 Abbey Plz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
Merged_dataset[Merged_dataset.duplicated()] #Shows duplicated rows
#Merged_dataset.drop_duplicates()

Empty DataFrame
Columns: [Reference_ID, Given_Name, Last_Name, Departments, Received_At, University, Citizenship, Intake, Phone_Number, Street_1, City, Region, Postal, Email_ID, Date_of_Birth, Most_Recent_Released_Decision, Application_Source, Is_Global_Grad, SEVIS_ID, Official_University_email_address, Application_Agency_Code, Created_At, Modified_At, Age, Deposit_Status, Assigned, Recieved_At, University_connect, I_20_Status, Created_At_connect, Modified_At_connect, SEVIS_ID_sevis, NonImmigrant_ID, SEVIS_Status, Status_Change_Date, Class_of_Admission, Surname_Or_Primary_Name, Given_Name_sevis, Preferred_Name, Country_of_Birth, Date_of_Birth_sevis, Country_of_Citizenship, Gender, Foreign_Address_1, Foreign_City, Foreign_Country, No_Phone_Indicator, Number_of_Months_(for_funding), Tuition_Fees, Living_Expenses, Dependent_Expenses, Other_Costs, Student's_Personal_Funds, Funds_From_This_School, School_Fund_Type, Funds_From_Other_Sources, Other_Source_Type, On-Campus_Employment, Date_of_Last_Event, School_Name, School_Code, Campus_Name, Campus_Code, I_20_Issue_Reason, Education_Level, Major_1_Code, Major_1_Description, Major_1_CIP_2020_Conversion, Major_2_Code, Major_2_CIP_2020_conversion, Minor_CIP_2020_Conversion, Program_Start_Date, Program_End_Date, Initial_Session_Start_Date, Current_Session_Start_Date, School_Requires_English_Proficiency, Student_Has_English_Proficiency, CPT_Approved, OCE_Requested, OCE_Approved, Pre-Completion_OPT_Requested, Pre-Completion_OPT_Approved, Post-Completion_OPT_Requested, Post-Completion_OPT_Approved, STEM_OPT_Requested, STEM_OPT_Approved, Cap_Gap_Extended, Student_Requested_Reinstatement, Student_Change_of_Status_Request, Student_Extension_Requested, Student_Authorized_to_Drop_Below_Full_Course_of_Study, Student_Transfer_Out, I-901_Transaction_Type, I-901_Transaction_Date, I-901_Transaction_Amount, I-901_Fee_Payment_Receipt, Border_Commuter_Student, Correction_Request_Pending, Overall_Remarks, OPT_Portal, ...]
Index: []

[0 rows x 116 columns]

In [101]:
Merged_dataset_1['Class_of_Admission'].unique()

array([nan, 'F-1'], dtype=object)

In [96]:
Merged_dataset.iloc[:, :20].head(5)

,Reference_ID,Given_Name,Last_Name,Departments,Received_At,University,Citizenship,Intake,Phone_Number,Street_1,City,Region,Postal,Email_ID,Date_of_Birth,Most_Recent_Released_Decision,Application_Source,Is_Global_Grad,SEVIS_ID,Official_University_email_address
0,1289258,Adekunle,Adefowoju,BusinessAdministration(MBA)ProfessionalMBA(Eve...,1970-01-01 00:29:04.630,Saint Louis University,Nigeria,Fall 2024,2350000000000,"9,HappinessEstateOffAmuleBusStopAyoboIpajaLago...",Lagos,LA,10001,henfakresources11@gmail.com,1997-06-28 12:50:22.429090944,2025-02-16 18:32:26.176644864,ERXWebAPP,Unknown,Unknown,adekunle.adefowoju@slu.edu
1,1294844,Emmanuel,AduNyarko,Analytics(MS)atSaintLouis,1970-01-01 00:29:04.630,Saint Louis University,Ghana,Fall 2024,233000000000,Plot11KwadwoAdjeistreet,Twumduase,Others,P.O.Boxup79,emmanueladunyarko33@gmail.com,1997-06-28 12:50:22.429090944,2025-02-16 18:32:26.176644864,ERXWebAPP,Unknown,Unknown,emmanuel.adunyarko@slu.edu
2,1302877,Ogochukwu,Agina,Analytics(MS)atSaintLouis,1970-01-01 00:29:04.630,Saint Louis University,Nigeria,Fall 2024,2350000000000,DClose206Road,FestacTown,Others,102312,o.agina@gmail.com,1997-06-28 12:50:22.429090944,2025-02-16 18:32:26.176644864,ERXWebAPP,Unknown,Unknown,ogochukwu.agina@slu.edu
3,1299192,Afia,AgyapongAnsong,InformationSystems(MS)atSaintLouis,1970-01-01 00:29:04.630,Saint Louis University,Ghana,Fall 2024,234000000000,45NiiTsawest,Accra,Others,0,afiakorantemaaansong40@gmail.com,1997-06-28 12:50:22.429090944,2025-02-16 18:32:26.176644864,ERXWebAPP,Unknown,Unknown,afia.agyapongansong@slu.edu
4,1324269,RebeccaAgyeiwaa,Agyare,PublicHealth(MPH)EpidemiologyatSaintLouis,1970-01-01 00:29:04.630,Saint Louis University,Ghana,Fall 2024,234000000000,GbaweCConnieTaxiRank,MallamGbawe,GreaterAccra,Others,rebeccaagyare67@gmail.com,1997-06-28 12:50:22.429090944,2025-02-16 18:32:26.176644864,INTO,Unknown,Unknown,rebeccaagyeiwaa.agyare@slu.edu

In [106]:
Merged_dataset_1.iloc[:, 20:40].isna().sum()

Application_Agency_Code       0
Created_At                    0
Modified_At                   0
Age                           0
Deposit_Status               18
Assigned                     18
Recieved_At                  18
University_connect           18
I_20_Status                  18
Created_At_connect           18
Modified_At_connect          18
SEVIS_ID_sevis             6205
NonImmigrant_ID            6205
SEVIS_Status               6205
Status_Change_Date         6205
Class_of_Admission         6205
Surname_Or_Primary_Name    6205
Given_Name_sevis           6205
Preferred_Name             6205
Country_of_Birth           6205
dtype: int64

In [ ]:
Merged_dataset.drop('Created_At_connect', axis= 1, inplace=True)
Merged_dataset.drop('Modified_At_connect', axis= 1, inplace=True)
Merged_dataset.drop('University_connect', axis= 1, inplace=True)
Merged_dataset.drop('SEVIS_ID_sevis', axis= 1, inplace=True)
Merged_dataset.drop('Country_of_Birth', axis= 1, inplace=True)
Merged_dataset.drop('Surname_Or_Primary_Name', axis= 1, inplace=True)
Merged_dataset.drop('Given_Name_sevis', axis= 1, inplace=True)
Merged_dataset.drop('Preferred_Name', axis= 1, inplace=True)
Merged_dataset.drop('Date_of_Birth_sevis ', axis= 1, inplace=True)
Merged_dataset.drop('Country_of_Citizenship', axis= 1, inplace=True)
Merged_dataset.drop('Application_Source_outreach', axis= 1, inplace=True)
Merged_dataset.drop('SEVIS_ID_outreach', axis= 1, inplace=True)

In [ ]:
#Export = df_copied.to_excel("Applicant.xlsx", sheet_name = "Applicant", index = False)
#Export

In [ ]:
#Export2 = df_copied2.to_excel("Connect.xlsx", sheet_name = "Connect", index = False)
#Export2

In [ ]:
#Export3 = df_copied3.to_excel("Outreach.xlsx", sheet_name = "Outreach", index = False)
#Export3

In [ ]:
#Export4 = df_copied4.to_excel("Sevis.xlsx", sheet_name = "Sevis", index = False)
#Export4